import { registerUiMessages, type UiMessageValue } from '@/lib/uiMessages'

export const homeZhMessages = {
  'home.hero.eyebrow': '超长篇续写引擎',
  'home.hero.title': '先理解世界，再写出好故事',
  'home.hero.description': '连载写到几百万字，设定还能不打架？NovWr 从你的正文中提取角色、势力、世界规则，构建结构化世界模型——续写时 AI 看到的不是零散章节，而是你整个世界观。',
  'home.hero.cta': '开始写作',
  'home.hero.cta.demo': '试用西游记 Demo',
  'home.hero.stat.demo.unit': '章',
  'home.hero.stat.demo.label': '真实 Demo',
  'home.hero.stat.entities.unit': '个',
  'home.hero.stat.entities.label': '实体提取',
  'home.hero.stat.systems.unit': '套',
  'home.hero.stat.systems.label': '世界体系',
  'home.feature.section.eyebrow': '三个界面',
  'home.feature.section.title': '写作台、世界地图、AI 助手——围绕同一部小说协同工作。',
  'home.feature.section.description': '三个界面共享同一套世界设定。在任何一处做的修改，其他地方实时生效。',
  'home.feature.studio.eyebrow': '写作台',
  'home.feature.studio.title': '读、写、续写，都在一个地方',
  'home.feature.studio.description': '左边翻章节，中间读原文或写新内容，右边呼出助手。写作、审阅、续写不用切换窗口。',
  'home.feature.studio.alt': 'NovWr 写作台界面',
  'home.feature.atlas.eyebrow': '世界地图',
  'home.feature.atlas.title': '你的世界设定，终于好看了',
  'home.feature.atlas.description': '人物档案、势力关系、力量体系——不再散落在文档和 Excel 里，而是一张可浏览、可编辑的结构化地图。',
  'home.feature.atlas.alt': 'NovWr 世界地图界面',
  'home.feature.copilot.eyebrow': 'AI 助手',
  'home.feature.copilot.title': '查设定不再翻稿',
  'home.feature.copilot.description': '问一句话，AI 从你的正文里找答案，附上出处段落。不是猜测，每条回答都能回溯验证。',
  'home.feature.copilot.alt': 'NovWr AI 助手界面',
  'home.workflow.eyebrow': '工作流程',
  'home.workflow.title': '五步走完，从原文到续写。',
  'home.workflow.description': '从正文导入到成品续写，每一步都围绕你的小说展开。',
  'home.workflow.currentStep': '当前步骤',
  // ── Act 1: Import ──
  'home.narrative.act1.eyebrow': '导入',
  'home.narrative.act1.title': '把稿子丢进来，人物关系自己长出来',
  'home.narrative.act1.description': '连载几百万字，角色在第几章出过场谁还记得清？把正文交给 NovWr，它逐章阅读，自动提取人物、地点和势力关系——散落在脑子里的角色网络，变成一张可查可改的结构化地图。',
  'home.narrative.act1.bullet1': '百万字级正文，几分钟内提取角色关系网络',
  'home.narrative.act1.bullet2': '"这个人第几章出场过？"——以后不用翻稿子了',
  'home.narrative.act1.bullet3': '零手动标注，实体和关系开箱可用',
  // ── Act 2: Settings / Build ──
  'home.narrative.act2.eyebrow': '基建',
  'home.narrative.act2.title': '世界的规则，往往不在正文里',
  'home.narrative.act2.description': '正文记录了谁做了什么，但修炼体系怎么分级、阵营之间什么势力格局——这些往往只存在于作者的脑子里。把你的设定文本粘贴进来，NovWr 生成结构化的世界体系，和导入提取的实体关系合在一起，构成完整世界模型。',
  'home.narrative.act2.bullet1': '力量体系、阵营法则、世界规则——正文提取不到的，在这里补全',
  'home.narrative.act2.bullet2': '和第一步提取的实体关系互补，拼成完整世界模型',
  'home.narrative.act2.bullet3': '生成结果先进草稿队列，下一步审核确认',
  // ── Act 3: Governance / Review ──
  'home.narrative.act3.eyebrow': '审核',
  'home.narrative.act3.title': 'AI 先出草稿，你再逐条定稿',
  'home.narrative.act3.description': '前两步提取和生成的内容不会直接写进世界模型。NovWr 把它们送进审核队列，按实体、关系、体系分开；你逐条确认、修改或拒绝，确认过的内容才正式生效。',
  'home.narrative.act3.bullet1': '实体、关系、体系分开排队，先处理最密的那一类',
  'home.narrative.act3.bullet2': '每条草稿都能确认、拒绝或补写，不必在总览里盲找',
  'home.narrative.act3.bullet3': '只有你确认过的内容，AI 续写时才会严格遵守',
  // ── Act 4: Copilot ──
  'home.narrative.act4.eyebrow': '查阅',
  'home.narrative.act4.title': '灵感来了，不用停下来翻笔记',
  'home.narrative.act4.description': '写到关键情节想确认细节？直接问 AI 助手。它从你的正文中定位答案并附上原文出处，不用退出写作界面。',
  'home.narrative.act4.bullet1': '"这个角色上次出场时什么状态？"——几秒内给出回答',
  'home.narrative.act4.bullet2': '发现设定空白？助手会提示哪些人物、地点、物品还缺关键信息',
  'home.narrative.act4.bullet3': '回答附带原文引用，不放心时一键跳转核实',
  // ── Act 5: Continuation ──
  'home.narrative.act5.eyebrow': '续写',
  'home.narrative.act5.title': '不是拼凑片段，是读懂世界后续写',
  'home.narrative.act5.description': '普通 AI 写作工具从碎片化原文推断世界信息，设定错乱在所难免。NovWr 把你确认过的角色性格、势力格局、世界规则结构化注入上下文——AI 续写拿到的是完整世界观，不是碎片。',
  'home.narrative.act5.bullet1': '角色说话像那个角色——人设来自你校准过的世界模型',
  'home.narrative.act5.bullet2': '一次生成多个版本，挑最顺眼的继续改',
  'home.narrative.act5.bullet3': '不满意就丢掉重来——好点子从来不怕被淘汰',
  // ── Closing CTA ──
  'home.cta.title': '你的世界，值得被认真对待',
  'home.cta.description': '从你已经写下的故事中构建结构化世界模型，再基于它续写——每条设定可查，每段续写有据。',
  'home.cta.stat.length': '100万+字',
  'home.cta.stat.length.label': '超长篇支持',
  'home.cta.stat.model': '结构化',
  'home.cta.stat.model.label': '世界模型',
  'home.cta.stat.context': '全书',
  'home.cta.stat.context.label': '上下文追踪',
  'home.cta.button': '免费开始写作',
  'home.cta.previewAlt': 'NovWr Studio 预览',
  'home.details.section.eyebrow': '设计细节',
  'home.details.section.title': '写长篇的人才知道这些细节有多重要。',
  'home.details.section.description': '不是功能堆砌，是我们反复推敲过的写作体验。',
  'home.details.card1.label': '设定漂移标注',
  'home.details.card1.description': '续写中注入的角色、地点、体系显示摘要，结束后高亮显示漂移——直观可见。',
  'home.details.card2.label': '表面与真相',
  'home.details.card2.description': '同一个实体可以有两层叙述——读者看到的"表面"和你才知道的"真相"。AI 只看表面，你的悬念安全。',
  'home.details.card3.label': '多候选续写',
  'home.details.card3.description': '一次生成几段候选，快速对比，不满意就扔。灵感不该被第一个结果绑架。',
  'home.details.card4.label': '出处引用',
  'home.details.card4.description': 'AI助手的每条回答都标注了来源章节和段落。有疑问？跳转原文核实。',
  // ── Stage window labels & captions ──
  'home.stage.window.library': 'NovWr Library',
  'home.stage.window.studio': 'NovWr Studio',
  'home.stage.window.atlas': 'NovWr Atlas',
  'home.stage.window.copilot': 'NovWr Copilot',
  'home.stage.caption.import': 'Library — 导入与章节管理',
  'home.stage.caption.settings': 'Atlas — 从设定文本生成世界体系',
  'home.stage.caption.governance': 'Atlas — 草稿审核与定稿',
  'home.stage.caption.copilot': 'Copilot — AI 研究助手',
  'home.stage.caption.continuation': 'Studio — 回到续写',
  // ── Scene overlay text (used by scene components) ──
  'home.scene.governance.eyebrow': '草稿审核',
  'home.scene.governance.queueLabel': '待审核',
  'home.scene.governance.title': '先排队，再定稿',
  'home.scene.governance.metric1.leading': '实体',
  'home.scene.governance.metric1.trailing': '119 条',
  'home.scene.governance.metric2.leading': '关系',
  'home.scene.governance.metric2.trailing': '优先处理',
  'home.scene.governance.metric3.leading': '确认后',
  'home.scene.governance.metric3.trailing': '续写才遵守',
  'home.scene.copilot.badge': '研究助手',
  'home.scene.copilot.description': '从全书证据中回答问题，而不是凭空补写。',
  'home.scene.copilot.pill': '证据支持回答',
  'home.scene.continuation.status': '续写就绪 · Context Loaded',
  'home.scene.continuation.contextLabel': '已注入上下文',
  'home.scene.continuation.contextChip1': '42 角色',
  'home.scene.continuation.contextChip2': '32 地点',
  'home.scene.continuation.contextChip3': '8 体系',
  'home.scene.continuation.contextChip4': '312 关系',
  'home.scene.continuation.readiness1.label': '世界模型',
  'home.scene.continuation.readiness1.value': '127 实体',
  'home.scene.continuation.readiness2.label': '设定校验',
  'home.scene.continuation.readiness2.value': '8 体系',
  'home.scene.continuation.readiness3.label': 'Copilot',
  'home.scene.continuation.readiness3.value': '就绪',
  'home.scene.continuation.evidenceTitle': '引用依据',
  'home.scene.continuation.evidence1.label': '第3回 §2',
  'home.scene.continuation.evidence1.desc': '师徒关系',
  'home.scene.continuation.evidence2.label': '第27回 §1',
  'home.scene.continuation.evidence2.desc': '八戒性格',
  'home.scene.continuation.evidence3.label': '第84回 §3',
  'home.scene.continuation.evidence3.desc': '前回衔接',
  'home.scene.settings.eyebrow': '从设定生成',
  'home.scene.settings.hint': '粘贴设定文本 → 生成世界体系',
  'home.scene.import.stat': '4 部作品',
} as const satisfies Record<string, UiMessageValue>

export const homeEnMessages = {
  'home.hero.eyebrow': 'NOVEL CONTINUATION ENGINE',
  'home.hero.title': 'Understand the world first.\nWrite better stories.',
  'home.hero.description': 'Long serials break when AI only sees the last few thousand words. NovWr extracts characters, factions, and world rules from your manuscript into a structured world model — then generates continuation grounded in the complete picture.',
  'home.hero.cta': 'Start writing',
  'home.hero.cta.demo': 'Try Journey to the West Demo',
  'home.narrative.act1.eyebrow': 'IMPORT',
  'home.narrative.act1.title': 'Drop your manuscript — characters and connections emerge on their own',
  'home.narrative.act1.description': 'Dozens of chapters in and you can\'t remember who showed up where? Hand NovWr your manuscript — it reads chapter by chapter, extracting characters, locations, and faction ties into a structured map you can browse and edit.',
  'home.narrative.act1.bullet1': 'Million-character manuscripts get a character relationship map within minutes',
  'home.narrative.act1.bullet2': '"When did this character show up?" — never dig through chapters again',
  'home.narrative.act1.bullet3': 'Zero manual tagging — entities and relationships work out of the box',
  'home.narrative.act2.eyebrow': 'BUILD',
  'home.narrative.act2.title': 'World rules rarely live inside the manuscript',
  'home.narrative.act2.description': 'Your text records who did what, but how power systems rank, how factions are structured — those live in the author\'s head. Paste your world-building notes and NovWr generates structured world systems that complement the entities and relationships extracted in step one.',
  'home.narrative.act2.bullet1': 'Power systems, faction rules, world laws — fill in what chapter extraction can\'t reach',
  'home.narrative.act2.bullet2': 'Complements step-one extraction to form a complete world model',
  'home.narrative.act2.bullet3': 'Results enter the draft queue — confirmed in the next step',
  'home.narrative.act3.eyebrow': 'REVIEW',
  'home.narrative.act3.title': 'AI drafts it first — you approve it line by line',
  'home.narrative.act3.description': 'Nothing from the first two steps writes itself directly into the world model. NovWr sends everything into a review queue, split by entities, relationships, and systems; you approve, edit, or reject each row before it becomes canon.',
  'home.narrative.act3.bullet1': 'Entities, relationships, and systems queue separately — clear the densest pile first',
  'home.narrative.act3.bullet2': 'Every draft row can be approved, rejected, or expanded — no blind hunting in a giant overview',
  'home.narrative.act3.bullet3': 'Only approved rows become canon — only canon guides continuation',
  'home.narrative.act4.eyebrow': 'LOOK UP',
  'home.narrative.act4.title': 'Inspiration struck — don\'t stop to flip through notes',
  'home.narrative.act4.description': 'Need to confirm a detail mid-scene? Ask the AI assistant — it locates the answer in your manuscript with source citations, without pulling you out of the writing surface.',
  'home.narrative.act4.bullet1': '"What was this character\'s state the last time they appeared?" — answered in seconds',
  'home.narrative.act4.bullet2': 'Spot a gap? The assistant flags characters still missing key details',
  'home.narrative.act4.bullet3': 'Every answer cites the source — one click to jump to the original passage',
  'home.narrative.act5.eyebrow': 'CONTINUE',
  'home.narrative.act5.title': 'Not stitching fragments — writing after understanding the world',
  'home.narrative.act5.description': 'Generic AI tools only see the last few thousand words — setting drift is inevitable. NovWr injects your confirmed character personalities, faction dynamics, and world rules into context before generating.',
  'home.narrative.act5.bullet1': 'Characters speak like themselves — grounded in the world model you calibrated',
  'home.narrative.act5.bullet2': 'Generate multiple versions, pick the one that fits, and keep going',
  'home.narrative.act5.bullet3': 'Don\'t like it? Throw it away and try again — good ideas aren\'t afraid of the cut',
  'home.cta.title': 'Your world-building shouldn\'t live only in your head.',
  'home.cta.description': 'NovWr builds a structured world model from what you\'ve already written, then generates continuation grounded in it. Every setting is traceable, every continuation has evidence.',
  'home.cta.stat.length': '500K+',
  'home.cta.stat.length.label': 'characters supported',
  'home.cta.stat.model': 'Structured',
  'home.cta.stat.model.label': 'world model',
  'home.cta.stat.context': 'Full-novel',
  'home.cta.stat.context.label': 'context tracking',
  'home.cta.button': 'Start writing for free',
  'home.hero.stat.demo.unit': 'chapters',
  'home.hero.stat.demo.label': 'live demo',
  'home.hero.stat.entities.unit': 'items',
  'home.hero.stat.entities.label': 'entities extracted',
  'home.hero.stat.systems.unit': 'systems',
  'home.hero.stat.systems.label': 'world systems',
  'home.feature.section.eyebrow': 'THREE SURFACES',
  'home.feature.section.title': 'Studio, Atlas, and Copilot all work on the same novel.',
  'home.feature.section.description': 'All three share one world model in real time. Change anything in one, and the others update instantly.',
  'home.feature.studio.eyebrow': 'STUDIO',
  'home.feature.studio.title': 'Read, write, and continue in one workspace',
  'home.feature.studio.description': 'Browse chapters on the left, read or write in the center, and open AI assistance on the right. Everything stays anchored to the chapter you\'re working on — no window-switching.',
  'home.feature.studio.alt': 'NovWr Studio workspace',
  'home.feature.atlas.eyebrow': 'ATLAS',
  'home.feature.atlas.title': 'Your world-building, finally visible',
  'home.feature.atlas.description': 'Character profiles, faction dynamics, power systems — no longer scattered across docs and spreadsheets, but a structured map you can browse and edit.',
  'home.feature.atlas.alt': 'NovWr Atlas workspace',
  'home.feature.copilot.eyebrow': 'COPILOT',
  'home.feature.copilot.title': 'Look up lore without leaving the page',
  'home.feature.copilot.description': 'Ask a question and the AI finds the answer in your manuscript, citing the source passage. Not a guess — every response links back to the original text.',
  'home.feature.copilot.alt': 'NovWr Copilot workspace',
  'home.workflow.eyebrow': 'WORKFLOW',
  'home.workflow.title': 'Five steps from raw text to grounded continuation.',
  'home.workflow.description': 'From raw manuscript to grounded continuation — every step stays tied to your novel.',
  'home.workflow.currentStep': 'Current step',
  'home.cta.previewAlt': 'NovWr Studio preview',
  'home.details.section.eyebrow': 'DETAILS',
  'home.details.section.title': 'Writers of long-form fiction know these details matter.',
  'home.details.section.description': 'Not a feature dump — design choices we deliberated over.',
  'home.details.card1.label': 'Entity highlights',
  'home.details.card1.description': 'Characters and locations in your continuation are color-tagged — if anything drifts from the world model, you see it instantly.',
  'home.details.card2.label': 'Surface vs. truth',
  'home.details.card2.description': 'Each entity can hold two narrative layers — the "surface" readers see and the "truth" only the author knows. AI sees surface only; your twists stay safe.',
  'home.details.card3.label': 'Multiple continuations',
  'home.details.card3.description': 'Generate several candidates at once, compare quickly, discard freely. Don\'t let the first result hold your inspiration hostage.',
  'home.details.card4.label': 'Source citations',
  'home.details.card4.description': 'Every Copilot answer tags the source chapter and paragraph. Unsure? One click to jump to the original text.',
  'home.stage.window.library': 'NovWr Library',
  'home.stage.window.studio': 'NovWr Studio',
  'home.stage.window.atlas': 'NovWr Atlas',
  'home.stage.window.copilot': 'NovWr Copilot',
  'home.stage.caption.import': 'Library — import and chapter management',
  'home.stage.caption.settings': 'Atlas — generate world systems from setting text',
  'home.stage.caption.governance': 'Atlas — draft review and sign-off',
  'home.stage.caption.copilot': 'Copilot — research assistant',
  'home.stage.caption.continuation': 'Studio — back to continuation',
  'home.scene.governance.eyebrow': 'Draft review',
  'home.scene.governance.queueLabel': 'Needs review',
  'home.scene.governance.title': 'Queue first. Approve second.',
  'home.scene.governance.metric1.leading': 'Entities',
  'home.scene.governance.metric1.trailing': '119 rows',
  'home.scene.governance.metric2.leading': 'Relations',
  'home.scene.governance.metric2.trailing': 'prioritized',
  'home.scene.governance.metric3.leading': 'Approved',
  'home.scene.governance.metric3.trailing': 'then writing obeys',
  'home.scene.copilot.badge': 'Research assistant',
  'home.scene.copilot.description': 'Answer from full-novel evidence instead of improvising from thin air.',
  'home.scene.copilot.pill': 'Evidence-backed answers',
  'home.scene.continuation.status': 'Continuation ready · context loaded',
  'home.scene.continuation.contextLabel': 'Context injected',
  'home.scene.continuation.contextChip1': '42 characters',
  'home.scene.continuation.contextChip2': '32 locations',
  'home.scene.continuation.contextChip3': '8 systems',
  'home.scene.continuation.contextChip4': '312 relations',
  'home.scene.continuation.readiness1.label': 'world model',
  'home.scene.continuation.readiness1.value': '127 entities',
  'home.scene.continuation.readiness2.label': 'consistency checks',
  'home.scene.continuation.readiness2.value': '8 systems',
  'home.scene.continuation.readiness3.label': 'Copilot',
  'home.scene.continuation.readiness3.value': 'ready',
  'home.scene.continuation.evidenceTitle': 'Grounding evidence',
  'home.scene.continuation.evidence1.label': 'Chapter 3 §2',
  'home.scene.continuation.evidence1.desc': 'master-disciple bond',
  'home.scene.continuation.evidence2.label': 'Chapter 27 §1',
  'home.scene.continuation.evidence2.desc': 'Bajie temperament',
  'home.scene.continuation.evidence3.label': 'Chapter 84 §3',
  'home.scene.continuation.evidence3.desc': 'handoff from prior chapter',
  'home.scene.settings.eyebrow': 'Generate from settings',
  'home.scene.settings.hint': 'Paste setting text → generate world systems',
  'home.scene.import.stat': '4 novels',
} as const satisfies Partial<Record<keyof typeof homeZhMessages, UiMessageValue>>

// Русский пакет сообщений главной (маркетинговой) страницы.
export const homeRuMessages = {
  'home.hero.eyebrow': 'Движок продолжения длинных романов',
  'home.hero.title': 'Сначала пойми мир — потом напиши хорошую историю',
  'home.hero.description': 'Сериал на миллионы знаков — и сеттинг всё ещё не разваливается? NovWr извлекает из вашего текста персонажей, фракции и правила мира и строит структурированную модель мира: при продолжении ИИ видит не разрозненные главы, а всю вашу вселенную.',
  'home.hero.cta': 'Начать писать',
  'home.hero.cta.demo': 'Попробовать демо «Путешествие на Запад»',
  'home.hero.stat.demo.unit': 'глав',
  'home.hero.stat.demo.label': 'живое демо',
  'home.hero.stat.entities.unit': 'шт.',
  'home.hero.stat.entities.label': 'извлечено сущностей',
  'home.hero.stat.systems.unit': 'шт.',
  'home.hero.stat.systems.label': 'систем мира',
  'home.feature.section.eyebrow': 'Три интерфейса',
  'home.feature.section.title': 'Студия, карта мира и ИИ-помощник — работают вместе над одним романом.',
  'home.feature.section.description': 'Три интерфейса используют одну и ту же модель мира. Изменение в любом из них мгновенно отражается в остальных.',
  'home.feature.studio.eyebrow': 'Студия',
  'home.feature.studio.title': 'Читать, писать и продолжать — в одном месте',
  'home.feature.studio.description': 'Слева — главы, в центре — чтение или новый текст, справа — помощник. Написание, проверка и продолжение без переключения окон.',
  'home.feature.studio.alt': 'Интерфейс студии NovWr',
  'home.feature.atlas.eyebrow': 'Карта мира',
  'home.feature.atlas.title': 'Ваш сеттинг наконец выглядит достойно',
  'home.feature.atlas.description': 'Досье персонажей, отношения фракций, системы сил — больше не разбросаны по документам и таблицам, а собраны в структурированную карту, которую можно просматривать и редактировать.',
  'home.feature.atlas.alt': 'Интерфейс карты мира NovWr',
  'home.feature.copilot.eyebrow': 'ИИ-помощник',
  'home.feature.copilot.title': 'Проверяйте сеттинг, не листая рукопись',
  'home.feature.copilot.description': 'Задайте вопрос — ИИ найдёт ответ в вашем тексте и приложит абзац-источник. Это не догадки: каждый ответ можно проверить по первоисточнику.',
  'home.feature.copilot.alt': 'Интерфейс ИИ-помощника NovWr',
  'home.workflow.eyebrow': 'Рабочий процесс',
  'home.workflow.title': 'Пять шагов — от исходного текста до продолжения.',
  'home.workflow.description': 'От импорта рукописи до готового продолжения — каждый шаг строится вокруг вашего романа.',
  'home.workflow.currentStep': 'Текущий шаг',
  // ── Акт 1: Импорт ──
  'home.narrative.act1.eyebrow': 'Импорт',
  'home.narrative.act1.title': 'Забросьте рукопись — связи персонажей вырастут сами',
  'home.narrative.act1.description': 'Кто вспомнит, в какой главе появлялся герой, когда в сериале миллионы знаков? Передайте текст NovWr: он читает главу за главой и автоматически извлекает персонажей, места и связи фракций — сеть героев из вашей головы превращается в структурированную карту, которую можно просматривать и править.',
  'home.narrative.act1.bullet1': 'Рукописи на миллионы знаков — сеть отношений персонажей за считаные минуты',
  'home.narrative.act1.bullet2': '«В какой главе появлялся этот герой?» — больше не нужно листать рукопись',
  'home.narrative.act1.bullet3': 'Ноль ручной разметки — сущности и связи работают сразу',
  // ── Акт 2: Сеттинг / Постройка ──
  'home.narrative.act2.eyebrow': 'Постройка',
  'home.narrative.act2.title': 'Правила мира редко живут в самом тексте',
  'home.narrative.act2.description': 'Текст фиксирует, кто что сделал, но ранги системы культивации и расстановка сил между лагерями обычно существуют только в голове автора. Вставьте свои заметки о мире — NovWr сгенерирует структурированные системы мира, которые вместе с извлечёнными сущностями и связями складываются в полную модель мира.',
  'home.narrative.act2.bullet1': 'Системы сил, законы фракций, правила мира — здесь дополняется то, что нельзя извлечь из текста',
  'home.narrative.act2.bullet2': 'Дополняет извлечённые на первом шаге сущности и связи до полной модели мира',
  'home.narrative.act2.bullet3': 'Результаты генерации сначала попадают в очередь черновиков, затем — на проверку',
  // ── Акт 3: Проверка ──
  'home.narrative.act3.eyebrow': 'Проверка',
  'home.narrative.act3.title': 'ИИ готовит черновик — вы утверждаете построчно',
  'home.narrative.act3.description': 'Результаты первых двух шагов не записываются в модель мира напрямую. NovWr отправляет их в очередь проверки, разделяя на сущности, связи и системы; вы подтверждаете, правите или отклоняете каждую запись — в силу вступает только подтверждённое.',
  'home.narrative.act3.bullet1': 'Сущности, связи и системы стоят в отдельных очередях — начните с самой плотной',
  'home.narrative.act3.bullet2': 'Каждый черновик можно подтвердить, отклонить или дописать — без слепого поиска в общем списке',
  'home.narrative.act3.bullet3': 'ИИ при продолжении строго следует только тому, что вы подтвердили',
  // ── Акт 4: Справки ──
  'home.narrative.act4.eyebrow': 'Справки',
  'home.narrative.act4.title': 'Пришло вдохновение — не отвлекайтесь на заметки',
  'home.narrative.act4.description': 'Нужно уточнить деталь в ключевой сцене? Спросите ИИ-помощника. Он найдёт ответ в вашем тексте и приложит цитату-источник — не выходя из интерфейса написания.',
  'home.narrative.act4.bullet1': '«В каком состоянии этот герой появлялся в прошлый раз?» — ответ за секунды',
  'home.narrative.act4.bullet2': 'Нашли пробел в сеттинге? Помощник подскажет, каким персонажам, местам и предметам не хватает ключевых данных',
  'home.narrative.act4.bullet3': 'Ответы сопровождаются цитатами — сомневаетесь? Один клик, и вы у первоисточника',
  // ── Акт 5: Продолжение ──
  'home.narrative.act5.eyebrow': 'Продолжение',
  'home.narrative.act5.title': 'Не склейка фрагментов, а продолжение после понимания мира',
  'home.narrative.act5.description': 'Обычные ИИ-инструменты восстанавливают мир по обрывкам текста — путаница в сеттинге неизбежна. NovWr структурированно внедряет в контекст подтверждённые вами характеры, расстановку сил и правила мира: ИИ продолжает, опираясь на целую вселенную, а не на фрагменты.',
  'home.narrative.act5.bullet1': 'Персонаж говорит как он сам — образ берётся из выверенной вами модели мира',
  'home.narrative.act5.bullet2': 'Несколько версий за одну генерацию — выберите лучшую и продолжайте',
  'home.narrative.act5.bullet3': 'Не понравилось — выбрасывайте и пробуйте снова: хорошие идеи не боятся отбора',
  // ── Финальный призыв ──
  'home.cta.title': 'Ваш мир заслуживает серьёзного отношения',
  'home.cta.description': 'Постройте структурированную модель мира из уже написанной истории и продолжайте на её основе — каждая деталь сеттинга проверяема, каждое продолжение обосновано.',
  'home.cta.stat.length': '1 млн+ знаков',
  'home.cta.stat.length.label': 'поддержка сверхдлинных романов',
  'home.cta.stat.model': 'Структурированная',
  'home.cta.stat.model.label': 'модель мира',
  'home.cta.stat.context': 'Вся книга',
  'home.cta.stat.context.label': 'отслеживание контекста',
  'home.cta.button': 'Начать писать бесплатно',
  'home.cta.previewAlt': 'Предпросмотр NovWr Studio',
  'home.details.section.eyebrow': 'Детали дизайна',
  'home.details.section.title': 'Только авторы длинной прозы знают, насколько важны эти детали.',
  'home.details.section.description': 'Не нагромождение функций, а многократно выверенный писательский опыт.',
  'home.details.card1.label': 'Пометки дрейфа сеттинга',
  'home.details.card1.description': 'Персонажи, места и системы, внедрённые в продолжение, показываются в сводке, а после завершения дрейф подсвечивается — всё наглядно.',
  'home.details.card2.label': 'Внешнее и истинное',
  'home.details.card2.description': 'У одной сущности может быть два слоя повествования — «внешнее», которое видят читатели, и «истина», известная только вам. ИИ видит только внешнее — ваша интрига в безопасности.',
  'home.details.card3.label': 'Несколько кандидатов продолжения',
  'home.details.card3.description': 'Несколько кандидатов за одну генерацию: быстро сравнивайте, не понравилось — выбрасывайте. Вдохновение не должно зависеть от первого результата.',
  'home.details.card4.label': 'Цитирование источников',
  'home.details.card4.description': 'Каждый ответ ИИ-помощника снабжён ссылкой на главу и абзац. Сомневаетесь? Перейдите к первоисточнику и проверьте.',
  // ── Подписи окон сцены ──
  'home.stage.window.library': 'NovWr Library',
  'home.stage.window.studio': 'NovWr Studio',
  'home.stage.window.atlas': 'NovWr Atlas',
  'home.stage.window.copilot': 'NovWr Copilot',
  'home.stage.caption.import': 'Library — импорт и управление главами',
  'home.stage.caption.settings': 'Atlas — генерация систем мира из текста сеттинга',
  'home.stage.caption.governance': 'Atlas — проверка черновиков и утверждение',
  'home.stage.caption.copilot': 'Copilot — ИИ-помощник для исследований',
  'home.stage.caption.continuation': 'Studio — назад к продолжению',
  // ── Текст оверлеев сцен ──
  'home.scene.governance.eyebrow': 'Проверка черновиков',
  'home.scene.governance.queueLabel': 'Ждут проверки',
  'home.scene.governance.title': 'Сначала очередь, потом утверждение',
  'home.scene.governance.metric1.leading': 'Сущности',
  'home.scene.governance.metric1.trailing': '119 записей',
  'home.scene.governance.metric2.leading': 'Связи',
  'home.scene.governance.metric2.trailing': 'в приоритете',
  'home.scene.governance.metric3.leading': 'После подтверждения',
  'home.scene.governance.metric3.trailing': 'продолжение следует им',
  'home.scene.copilot.badge': 'Помощник-исследователь',
  'home.scene.copilot.description': 'Отвечает на основе фактов из всей книги, а не выдумывает.',
  'home.scene.copilot.pill': 'Ответы с доказательствами',
  'home.scene.continuation.status': 'Продолжение готово · контекст загружен',
  'home.scene.continuation.contextLabel': 'Контекст внедрён',
  'home.scene.continuation.contextChip1': '42 персонажа',
  'home.scene.continuation.contextChip2': '32 места',
  'home.scene.continuation.contextChip3': '8 систем',
  'home.scene.continuation.contextChip4': '312 связей',
  'home.scene.continuation.readiness1.label': 'модель мира',
  'home.scene.continuation.readiness1.value': '127 сущностей',
  'home.scene.continuation.readiness2.label': 'проверка сеттинга',
  'home.scene.continuation.readiness2.value': '8 систем',
  'home.scene.continuation.readiness3.label': 'Copilot',
  'home.scene.continuation.readiness3.value': 'готов',
  'home.scene.continuation.evidenceTitle': 'Основания',
  'home.scene.continuation.evidence1.label': 'Глава 3 §2',
  'home.scene.continuation.evidence1.desc': 'связь учителя и ученика',
  'home.scene.continuation.evidence2.label': 'Глава 27 §1',
  'home.scene.continuation.evidence2.desc': 'характер Чжу Бацзе',
  'home.scene.continuation.evidence3.label': 'Глава 84 §3',
  'home.scene.continuation.evidence3.desc': 'связка с прошлой главой',
  'home.scene.settings.eyebrow': 'Генерация из сеттинга',
  'home.scene.settings.hint': 'Вставьте текст сеттинга → получите системы мира',
  'home.scene.import.stat': '4 произведения',
} as const satisfies Record<keyof typeof homeZhMessages, UiMessageValue>

export const homeUiMessages = {
  ru: homeRuMessages,
  zh: homeZhMessages,
  en: homeEnMessages,
} as const

registerUiMessages(homeUiMessages)
