import { registerUiMessages, type UiMessageValue } from '@/lib/uiMessages'

export const legalZhMessages = {
  'legal.lastUpdatedNote': ({ date }) => `最后更新 ${String(date ?? '')}`,
  'legal.contactLabel': '联系方式：',
  'legal.contactEmailLabel': '投诉邮箱：',
  'legal.contact.unconfigured': '部署前请设置 VITE_LEGAL_CONTACT_EMAIL',

  'terms.eyebrow': 'NovWr · 用户规则',
  'terms.title': '用户规则',
  'terms.summary': '本规则用于说明你在使用 NovWr 软件及相关服务时应遵守的基本要求、内容边界与处理方式。请在使用相关功能前仔细阅读。',
  'terms.scope.title': '1. 适用范围',
  'terms.scope.body1': '本规则适用于我们提供的 NovWr 官方网站、官方托管访问入口以及与 NovWr 软件发布相关的页面和服务。',
  'terms.scope.body2': '如你通过 Docker 或其他方式自行部署 NovWr，与你的部署环境、账号管理、数据存储、日志保留及对外运营相关的事项，由实际部署者自行负责。',
  'terms.service.title': '2. 服务性质',
  'terms.service.body1': 'NovWr 是一款基于人工智能的小说创作与续写辅助工具，提供文本续写、世界观整理与草稿生成能力。',
  'terms.service.body2': 'NovWr 生成的内容仅供创作参考，不构成法律、出版或知识产权意见，也不保证一定可直接公开发布。',
  'terms.upload.title': '3. 你可以上传什么',
  'terms.upload.item1': '你原创的小说、设定、角色资料与提示词；',
  'terms.upload.item2': '你已经取得明确授权的作品内容；',
  'terms.upload.item3': '属于公共领域，或依法可以使用的内容。',
  'terms.upload.body': '如你无法确认文本来源或授权状态，请勿上传或输入相关内容。',
  'terms.prohibited.title': '4. 你不能这样使用',
  'terms.prohibited.item1': '上传、续写、改写或传播未经授权的受版权保护作品；',
  'terms.prohibited.item2': '利用 NovWr 生成违法违规、侵权、诽谤、骚扰或其他有害内容；',
  'terms.prohibited.item3': '绕过服务限制、批量刷接口、攻击系统或影响他人正常使用。',
  'terms.ai.title': '5. AI 输出说明',
  'terms.ai.body1': 'AI 生成内容可能存在事实错误、风格漂移、与现有作品相似、设定冲突或不符合预期的情况。',
  'terms.ai.body2': '你在对外发布、投稿、商业使用或传播前，应自行完成审查、修改与风险判断。NovWr 不会将 AI 草稿视为最终成稿。',
  'terms.risk.title': '6. 我们如何处理风险内容',
  'terms.risk.body1': '如果我们发现，或收到第三方投诉认为相关内容存在侵权或违法违规风险，我们可以采取删除内容、隐藏结果、限制上传、暂停功能或终止服务等必要措施。',
  'terms.risk.body2': '对于重复侵权、明显高风险或恶意规避规则的使用行为，我们可直接限制继续使用。',
  'terms.related.title': '7. 相关页面',
  'terms.related.intro': '使用本服务前，也建议一并阅读',
  'terms.related.and': '与',
  'terms.related.outro': '。',

  'privacy.eyebrow': 'NovWr · 隐私说明',
  'privacy.title': '隐私说明',
  'privacy.summary': '本说明用于介绍我们在提供 NovWr 软件及相关服务过程中如何处理相关信息，包括处理范围、处理目的、保存方式以及你可以行使的相关权利。',
  'privacy.scope.title': '1. 适用范围',
  'privacy.scope.body1': '本说明适用于我们提供的 NovWr 官方网站、官方托管访问入口及相关服务。',
  'privacy.scope.body2': '如你使用的是第三方或自行部署的 NovWr 实例，相关信息处理规则应以实际部署者另行提供的说明为准。',
  'privacy.info.title': '2. 我们会处理哪些信息',
  'privacy.info.item1': '账号相关信息，如昵称、登录状态、基础配额信息；',
  'privacy.info.item2': '你主动上传或输入的内容，如章节正文、世界观设定、角色关系、续写指令；',
  'privacy.info.item3': 'NovWr 生成的结果，以及为保证服务可用而记录的基础日志与错误信息。',
  'privacy.purpose.title': '3. 我们为什么处理这些信息',
  'privacy.purpose.body1': '这些信息主要用于提供续写、保存作品、展示历史结果、处理故障、做基本风控，以及改进产品体验。',
  'privacy.purpose.body2': '除法律法规另有要求或经你另行授权外，我们不会超出实现服务所必需的范围使用相关信息。',
  'privacy.model.title': '4. 第三方模型服务',
  'privacy.model.body1': '当你发起生成请求时，相关章节上下文、世界设定和续写指令可能会被发送给当前接入的模型服务提供方，以完成生成任务。',
  'privacy.model.body2': '我们会尽量把传递范围控制在生成所必需的上下文内，但模型处理本身属于服务链路的一部分。',
  'privacy.retention.title': '5. 保存与删除',
  'privacy.retention.body1': '你上传的作品和生成结果通常会保留到你主动删除为止。你已经可以在作品库中删除作品，我们会同步清理相关文件与记录。',
  'privacy.retention.body2': '基础日志与安全记录仅在满足排障、安全防护和风险治理所需的合理期限内保留。',
  'privacy.choice.title': '6. 你的选择权',
  'privacy.choice.body1': '你可以决定是否上传作品、是否继续使用生成服务，以及是否删除已创建的作品。',
  'privacy.choice.body2': '如果你需要进一步删除账号、导出数据或反馈隐私问题，可通过以下方式联系我们：',

  'copyright.eyebrow': 'NovWr · 版权投诉',
  'copyright.title': '版权投诉说明',
  'copyright.summary': '如你认为通过 NovWr 官方托管入口提供或展示的相关内容侵犯了你的合法权益，可按本说明提交通知。我们将在收到完整材料后按流程进行核查与处理。',
  'copyright.scope.title': '1. 适用范围',
  'copyright.scope.body1': '本说明适用于通过 NovWr 官方托管访问入口提供或展示的相关内容。',
  'copyright.scope.body2': '如相关内容来自第三方或用户自行部署的 NovWr 实例，请优先联系对应实例的实际部署者或运营者处理。',
  'copyright.submit.title': '2. 如何提交投诉',
  'copyright.submit.body1': '如果你认为通过 NovWr 官方托管入口提供或展示的某些内容侵犯了你的合法权益，请尽量一次性提供完整信息，以便我们快速核查。',
  'copyright.submit.item1': '你的姓名或名称、联系方式；',
  'copyright.submit.item2': '能够证明你享有相关权利的材料或说明；',
  'copyright.submit.item3': '被投诉内容的标题、截图、链接或其他可定位信息；',
  'copyright.submit.item4': '你认为构成侵权的理由说明。',
  'copyright.action.title': '3. 我们会怎么做',
  'copyright.action.body1': '收到投诉后，我们会先做基础核查，并可能根据风险程度先行隐藏、删除、限制访问或暂停相关功能，以防问题继续扩大。',
  'copyright.action.body2': '如果用户多次上传高风险内容，我们可进一步限制其继续使用。',
  'copyright.counter.title': '4. 如果你是被投诉用户',
  'copyright.counter.body1': '如果你认为投诉存在误解，也可以主动联系我们说明情况，并补充你的授权、来源或创作证明材料。',
  'copyright.counter.body2': '在核查期间，我们可能根据具体情况暂时隐藏、删除或限制相关内容的访问与使用。',
  'copyright.contact.title': '5. 联系方式',
  'copyright.contact.missing': '当前未配置公开联系邮箱。正式对外发布前，请在环境变量中设置 `VITE_LEGAL_CONTACT_EMAIL`。',
} as const satisfies Record<string, UiMessageValue>
export const legalEnMessages = {
  'legal.lastUpdatedNote': ({ date }) => `Last updated ${String(date ?? '')}`,
  'legal.contactLabel': 'Contact:',
  'legal.contactEmailLabel': 'Complaint email:',
  'legal.contact.unconfigured': 'Set VITE_LEGAL_CONTACT_EMAIL before launch',

  'terms.eyebrow': 'NovWr · Terms',
  'terms.title': 'Terms of use',
  'terms.summary': 'These terms explain the basic rules, content boundaries, and handling policies that apply when you use NovWr and related services. Please read them before using the product.',
  'terms.scope.title': '1. Scope',
  'terms.scope.body1': 'These terms apply to the official NovWr website, the official hosted access entry, and related pages and services provided for NovWr releases.',
  'terms.scope.body2': 'If you deploy NovWr yourself with Docker or another method, the actual deployer is responsible for the deployment environment, account management, data storage, log retention, and any public operation of that instance.',
  'terms.service.title': '2. Nature of the service',
  'terms.service.body1': 'NovWr is an AI-assisted novel-writing and continuation tool that offers text continuation, world-model organization, and draft generation.',
  'terms.service.body2': 'Content generated by NovWr is for creative reference only. It is not legal, publishing, or intellectual-property advice, and it is not guaranteed to be ready for public release as-is.',
  'terms.upload.title': '3. What you may upload',
  'terms.upload.item1': 'Original novels, settings, character notes, and prompts that you created;',
  'terms.upload.item2': 'Works you are clearly authorized to use;',
  'terms.upload.item3': 'Content in the public domain or otherwise usable under applicable law.',
  'terms.upload.body': 'If you are not sure about the source of a text or whether you have permission to use it, do not upload or enter it.',
  'terms.prohibited.title': '4. Prohibited use',
  'terms.prohibited.item1': 'Uploading, continuing, rewriting, or distributing copyrighted works without authorization;',
  'terms.prohibited.item2': 'Using NovWr to generate illegal, infringing, defamatory, harassing, or otherwise harmful content;',
  'terms.prohibited.item3': 'Bypassing service limits, mass-abusing interfaces, attacking the system, or interfering with other users.',
  'terms.ai.title': '5. About AI output',
  'terms.ai.body1': 'AI-generated output may contain factual mistakes, style drift, accidental similarity to existing works, setting conflicts, or other results you did not intend.',
  'terms.ai.body2': 'Before publishing, submitting, commercializing, or distributing output, you are responsible for reviewing, editing, and making your own risk judgment. NovWr does not treat AI drafts as final manuscripts.',
  'terms.risk.title': '6. How we handle risky content',
  'terms.risk.body1': 'If we discover, or receive a complaint alleging, that content may be infringing, illegal, or otherwise risky, we may take necessary measures such as deleting content, hiding results, restricting uploads, suspending features, or terminating service.',
  'terms.risk.body2': 'We may directly restrict continued use in cases of repeated infringement, obviously high-risk content, or malicious attempts to evade the rules.',
  'terms.related.title': '7. Related pages',
  'terms.related.intro': 'Before using the service, we also recommend reading the',
  'terms.related.and': 'and',
  'terms.related.outro': '.',

  'privacy.eyebrow': 'NovWr · Privacy',
  'privacy.title': 'Privacy notice',
  'privacy.summary': 'This notice describes how we handle information when providing NovWr and related services, including what we process, why we process it, how we store it, and the rights you can exercise.',
  'privacy.scope.title': '1. Scope',
  'privacy.scope.body1': 'This notice applies to the official NovWr website, the official hosted access entry, and related services we provide.',
  'privacy.scope.body2': 'If you use a third-party or self-hosted NovWr instance, information handling for that instance is governed by the deployer’s own notice.',
  'privacy.info.title': '2. What information we process',
  'privacy.info.item1': 'Account-related information, such as nickname, sign-in state, and basic quota data;',
  'privacy.info.item2': 'Content that you actively upload or enter, such as chapter text, world settings, character relationships, and continuation instructions;',
  'privacy.info.item3': 'Generated results, plus basic logs and error information needed to keep the service available.',
  'privacy.purpose.title': '3. Why we process it',
  'privacy.purpose.body1': 'We process this information mainly to provide continuation, save works, show historical results, troubleshoot issues, perform basic risk controls, and improve the product experience.',
  'privacy.purpose.body2': 'Unless laws or regulations require otherwise, or you separately authorize us, we will not use the information beyond what is necessary to provide the service.',
  'privacy.model.title': '4. Third-party model services',
  'privacy.model.body1': 'When you send a generation request, related chapter context, world settings, and continuation instructions may be sent to the currently configured model provider so the request can be completed.',
  'privacy.model.body2': 'We try to keep the transmitted scope limited to the context required for generation, but model processing is part of the service chain itself.',
  'privacy.retention.title': '5. Retention and deletion',
  'privacy.retention.body1': 'Uploaded works and generated results are generally kept until you delete them. You can already delete novels from the library, and we will remove the related files and records together.',
  'privacy.retention.body2': 'Basic logs and security records are retained only for a reasonable period needed for troubleshooting, security protection, and risk management.',
  'privacy.choice.title': '6. Your choices',
  'privacy.choice.body1': 'You can decide whether to upload works, whether to keep using generation features, and whether to delete the works you created.',
  'privacy.choice.body2': 'If you need to delete an account, export data, or raise a privacy issue, contact us here:',

  'copyright.eyebrow': 'NovWr · Copyright',
  'copyright.title': 'Copyright notice',
  'copyright.summary': 'If you believe content provided or displayed through the official hosted NovWr entry infringes your lawful rights, you may submit a notice under this policy. We will review and handle complete submissions through our process.',
  'copyright.scope.title': '1. Scope',
  'copyright.scope.body1': 'This notice applies to content provided or displayed through the official hosted NovWr access entry.',
  'copyright.scope.body2': 'If the content comes from a third party or a user-operated NovWr instance, please contact that actual deployer or operator first.',
  'copyright.submit.title': '2. How to submit a complaint',
  'copyright.submit.body1': 'If you believe content provided or displayed through the official hosted NovWr entry infringes your lawful rights, please try to submit complete information in one pass so we can review it quickly.',
  'copyright.submit.item1': 'Your name or entity name and contact details;',
  'copyright.submit.item2': 'Materials or statements showing that you hold the relevant rights;',
  'copyright.submit.item3': 'The title, screenshot, link, or other locating information for the complained-about content;',
  'copyright.submit.item4': 'A statement of why you believe the content is infringing.',
  'copyright.action.title': '3. What we may do',
  'copyright.action.body1': 'After receiving a complaint, we will first conduct a basic review and may hide, delete, restrict access to, or suspend related content or features in advance depending on the risk level so the issue does not expand.',
  'copyright.action.body2': 'If a user repeatedly uploads high-risk content, we may further restrict continued use.',
  'copyright.counter.title': '4. If you are the reported user',
  'copyright.counter.body1': 'If you believe a complaint is based on a misunderstanding, you may also contact us proactively and provide supplementary proof of authorization, source, or creation.',
  'copyright.counter.body2': 'During review, we may temporarily hide, delete, or limit access to or use of the related content depending on the circumstances.',
  'copyright.contact.title': '5. Contact',
  'copyright.contact.missing': 'No public contact email is configured yet. Before a public launch, set `VITE_LEGAL_CONTACT_EMAIL` in the environment.',
} as const satisfies Record<keyof typeof legalZhMessages, UiMessageValue>

// Русский пакет юридических страниц (правила, конфиденциальность, авторские права).
export const legalRuMessages = {
  'legal.lastUpdatedNote': ({ date }) => `Последнее обновление: ${String(date ?? '')}`,
  'legal.contactLabel': 'Контакты:',
  'legal.contactEmailLabel': 'Почта для жалоб:',
  'legal.contact.unconfigured': 'Перед развёртыванием задайте VITE_LEGAL_CONTACT_EMAIL',

  'terms.eyebrow': 'NovWr · Правила использования',
  'terms.title': 'Правила использования',
  'terms.summary': 'Эти правила описывают базовые требования, границы допустимого контента и порядок обработки при использовании программы NovWr и связанных сервисов. Пожалуйста, внимательно прочитайте их перед использованием.',
  'terms.scope.title': '1. Область применения',
  'terms.scope.body1': 'Правила распространяются на официальный сайт NovWr, официальную размещённую (hosted) точку доступа, а также страницы и сервисы, связанные с выпуском программы NovWr.',
  'terms.scope.body2': 'Если вы разворачиваете NovWr самостоятельно (через Docker или иначе), за среду развёртывания, управление аккаунтами, хранение данных, ведение журналов и публичную эксплуатацию отвечает лицо, выполнившее развёртывание.',
  'terms.service.title': '2. Характер сервиса',
  'terms.service.body1': 'NovWr — инструмент помощи в написании и продолжении романов на основе искусственного интеллекта, предоставляющий продолжение текста, систематизацию мира и генерацию черновиков.',
  'terms.service.body2': 'Сгенерированный NovWr контент предназначен только для творческой справки, не является юридической, издательской или патентной консультацией и не гарантированно готов к публикации как есть.',
  'terms.upload.title': '3. Что можно загружать',
  'terms.upload.item1': 'ваши оригинальные романы, сеттинг, материалы о персонажах и промпты;',
  'terms.upload.item2': 'произведения, на использование которых у вас есть явное разрешение;',
  'terms.upload.item3': 'контент из общественного достояния или иной контент, использование которого допускается законом.',
  'terms.upload.body': 'Если вы не можете подтвердить источник текста или права на него — не загружайте и не вводите такой контент.',
  'terms.prohibited.title': '4. Что запрещено',
  'terms.prohibited.item1': 'загружать, продолжать, переписывать или распространять охраняемые авторским правом произведения без разрешения;',
  'terms.prohibited.item2': 'использовать NovWr для генерации незаконного, нарушающего чужие права, клеветнического, оскорбительного или иного вредоносного контента;',
  'terms.prohibited.item3': 'обходить ограничения сервиса, массово злоупотреблять интерфейсами, атаковать систему или мешать другим пользователям.',
  'terms.ai.title': '5. Об ИИ-выводе',
  'terms.ai.body1': 'Сгенерированный ИИ контент может содержать фактические ошибки, дрейф стиля, сходство с существующими произведениями, конфликты сеттинга или иные неожиданные результаты.',
  'terms.ai.body2': 'Перед публикацией, подачей в издательство, коммерческим использованием или распространением вы самостоятельно выполняете проверку, правку и оценку рисков. NovWr не считает ИИ-черновики готовой рукописью.',
  'terms.risk.title': '6. Как мы обрабатываем рискованный контент',
  'terms.risk.body1': 'Если мы обнаружим или получим жалобу третьих лиц о том, что контент может нарушать права или закон, мы можем принять необходимые меры: удалить контент, скрыть результаты, ограничить загрузки, приостановить функции или прекратить обслуживание.',
  'terms.risk.body2': 'При повторных нарушениях, явно высокорисковом контенте или злонамеренном обходе правил мы можем сразу ограничить дальнейшее использование.',
  'terms.related.title': '7. Связанные страницы',
  'terms.related.intro': 'Перед использованием сервиса рекомендуем также ознакомиться со страницами',
  'terms.related.and': 'и',
  'terms.related.outro': '.',

  'privacy.eyebrow': 'NovWr · Конфиденциальность',
  'privacy.title': 'Политика конфиденциальности',
  'privacy.summary': 'Этот документ описывает, как мы обрабатываем информацию при предоставлении программы NovWr и связанных сервисов: что обрабатывается, зачем, как хранится и какими правами вы располагаете.',
  'privacy.scope.title': '1. Область применения',
  'privacy.scope.body1': 'Документ распространяется на официальный сайт NovWr, официальную размещённую точку доступа и связанные сервисы.',
  'privacy.scope.body2': 'Если вы используете сторонний или самостоятельно развёрнутый экземпляр NovWr, правила обработки информации определяются документами лица, выполнившего развёртывание.',
  'privacy.info.title': '2. Какую информацию мы обрабатываем',
  'privacy.info.item1': 'данные аккаунта: никнейм, состояние входа, базовые сведения о квоте;',
  'privacy.info.item2': 'контент, который вы загружаете или вводите: текст глав, сеттинг мира, отношения персонажей, указания для продолжения;',
  'privacy.info.item3': 'результаты, сгенерированные NovWr, а также базовые журналы и сведения об ошибках, необходимые для работоспособности сервиса.',
  'privacy.purpose.title': '3. Зачем мы обрабатываем эту информацию',
  'privacy.purpose.body1': 'Информация используется в основном для предоставления продолжения, сохранения произведений, показа истории результатов, устранения неполадок, базового контроля рисков и улучшения продукта.',
  'privacy.purpose.body2': 'Если иное не требуется законодательством или отдельно не разрешено вами, мы не используем информацию сверх необходимого для предоставления сервиса.',
  'privacy.model.title': '4. Сторонние модельные сервисы',
  'privacy.model.body1': 'При запросе генерации соответствующий контекст глав, сеттинг мира и указания для продолжения могут передаваться подключённому поставщику модели для выполнения задачи.',
  'privacy.model.body2': 'Мы стараемся ограничивать передаваемый объём контекстом, необходимым для генерации, но обработка моделью — часть цепочки сервиса.',
  'privacy.retention.title': '5. Хранение и удаление',
  'privacy.retention.body1': 'Загруженные произведения и результаты генерации обычно хранятся до тех пор, пока вы их не удалите. Вы уже можете удалять произведения из библиотеки — вместе с ними мы удалим связанные файлы и записи.',
  'privacy.retention.body2': 'Базовые журналы и записи безопасности хранятся лишь в течение разумного срока, необходимого для диагностики, защиты и управления рисками.',
  'privacy.choice.title': '6. Ваши права выбора',
  'privacy.choice.body1': 'Вы сами решаете, загружать ли произведения, продолжать ли пользоваться генерацией и удалять ли созданные произведения.',
  'privacy.choice.body2': 'Если вам нужно удалить аккаунт, выгрузить данные или сообщить о проблеме конфиденциальности, свяжитесь с нами:',

  'copyright.eyebrow': 'NovWr · Авторские права',
  'copyright.title': 'Порядок подачи жалоб на нарушение авторских прав',
  'copyright.summary': 'Если вы считаете, что контент, предоставляемый или отображаемый через официальную размещённую точку доступа NovWr, нарушает ваши законные права, вы можете подать уведомление согласно этому документу. Получив полный комплект материалов, мы проверим и обработаем его по установленной процедуре.',
  'copyright.scope.title': '1. Область применения',
  'copyright.scope.body1': 'Документ распространяется на контент, предоставляемый или отображаемый через официальную размещённую точку доступа NovWr.',
  'copyright.scope.body2': 'Если контент исходит от третьих лиц или самостоятельно развёрнутого экземпляра NovWr, сначала обратитесь к лицу, которое фактически развернуло или эксплуатирует этот экземпляр.',
  'copyright.submit.title': '2. Как подать жалобу',
  'copyright.submit.body1': 'Если вы считаете, что контент официальной размещённой точки доступа NovWr нарушает ваши права, постарайтесь предоставить полный комплект информации сразу, чтобы мы могли быстро провести проверку.',
  'copyright.submit.item1': 'ваше имя или наименование и контактные данные;',
  'copyright.submit.item2': 'материалы или пояснения, подтверждающие ваши права;',
  'copyright.submit.item3': 'название, скриншот, ссылку или иные сведения, позволяющие найти оспариваемый контент;',
  'copyright.submit.item4': 'обоснование того, почему вы считаете контент нарушающим права.',
  'copyright.action.title': '3. Что мы предпримем',
  'copyright.action.body1': 'Получив жалобу, мы проведём базовую проверку и в зависимости от уровня риска можем заранее скрыть, удалить, ограничить доступ или приостановить соответствующие функции, чтобы проблема не разрасталась.',
  'copyright.action.body2': 'Если пользователь неоднократно загружает высокорисковый контент, мы можем дополнительно ограничить его использование сервиса.',
  'copyright.counter.title': '4. Если жалоба подана на вас',
  'copyright.counter.body1': 'Если вы считаете жалобу недоразумением, свяжитесь с нами и предоставьте подтверждение разрешения, источника или собственного авторства.',
  'copyright.counter.body2': 'На время проверки мы можем временно скрыть, удалить или ограничить доступ к соответствующему контенту в зависимости от обстоятельств.',
  'copyright.contact.title': '5. Контакты',
  'copyright.contact.missing': 'Публичный контактный e-mail пока не настроен. Перед публичным запуском задайте `VITE_LEGAL_CONTACT_EMAIL` в переменных окружения.',
} as const satisfies Record<keyof typeof legalZhMessages, UiMessageValue>

export const legalUiMessages = {
  ru: legalRuMessages,
  zh: legalZhMessages,
  en: legalEnMessages,
} as const

registerUiMessages(legalUiMessages)
