import { registerUiMessages, type UiMessageParams, type UiMessageValue } from '@/lib/uiMessages'

export const worldModelZhMessages = {
  'worldModel.common.all': '全部',
  'worldModel.common.entities': '实体',
  'worldModel.common.relationships': '关系',
  'worldModel.common.systems': '体系',
  'worldModel.common.draftReview': '草稿审核',
  'worldModel.common.statusDraft': '草稿',
  'worldModel.common.statusConfirmed': '已确认',
  'worldModel.common.view': '查看',
  'worldModel.common.locate': '定位',
  'worldModel.common.reject': '拒绝',
  'worldModel.common.retry': '重试',
  'worldModel.common.processing': '处理中...',
  'worldModel.common.file': '文件',
  'worldModel.common.pack': '包',
  'worldModel.common.notes': '注意事项',
  'worldModel.common.created': '新增',
  'worldModel.common.updated': '更新',
  'worldModel.common.deleted': '删除',
  'worldModel.common.none': '无',
  'worldModel.common.remove': '移除',
  'worldModel.common.visibility': '可见性',
  'worldModel.common.description': '描述',
  'worldModel.common.aliases': '别名',
  'worldModel.common.visibilityActive': '活跃',
  'worldModel.common.visibilityReference': '参考',
  'worldModel.common.visibilityHidden': '隐藏',
  'worldModel.common.unknownNode': '未知节点',
  'worldModel.common.unnamedNode': ({ index }) => `未命名节点 ${String(index ?? 0)}`,
  'worldModel.common.searchDrafts': '搜索草稿...',
  'worldModel.common.searchEntities': '搜索实体...',
  'worldModel.common.searchSystems': '搜索体系...',

  'worldModel.atlas.returnToStudio': '返回工作台',
  'worldModel.atlas.reviewTab': '草稿审核',
  'worldModel.atlas.startEditingSystem': '选择一个体系开始编辑',
  'worldModel.atlas.assist.eyebrow': '小说助手',
  'worldModel.atlas.assist.title': '辅助治理',
  'worldModel.atlas.assist.description': '左侧 navigator 只负责扫描与选择；右侧才是 Atlas 的研究、同步与审阅辅助区。',
  'worldModel.atlas.assist.researchEyebrow': '查设定',
  'worldModel.atlas.assist.wholeBookAction': '检索全书设定',
  'worldModel.atlas.assist.contextEntityTitle': '检查当前实体',
  'worldModel.atlas.assist.contextEntityHint': '补充这个实体的设定、证据和可能关系。',
  'worldModel.atlas.assist.contextRelationshipTitle': '检查当前关系',
  'worldModel.atlas.assist.contextRelationshipHint': '看看当前实体和其他角色有什么关系、哪里可能冲突。',
  'worldModel.atlas.assist.contextReviewTitle': '草稿整理',
  'worldModel.atlas.assist.contextReviewHint': '在批量审核前，先检查命名不一致、缺字段和明显冲突。',
  'worldModel.atlas.assist.governanceEyebrow': '生成与审核',
  'worldModel.atlas.assist.queueTitle': '待审核草稿',
  'worldModel.atlas.assist.queueHint': ({ count }: UiMessageParams) => `${String(count ?? 0)} 条草稿等待审核`,
  'worldModel.atlas.assist.queueEmpty': '当前没有待审核草稿',
  'worldModel.atlas.assist.reviewReadyTitle': '草稿已经准备好，下一步去审核',
  'worldModel.atlas.assist.reviewReadyDescription': 'Atlas 已经接到新的治理输入；下一步进入草稿审核，而不是继续停在当前列表里。',
  'worldModel.atlas.assist.runningTitle': '正在同步世界草稿',
  'worldModel.atlas.assist.runningDescription': '处理完成前不需要强制切换 tab；完成后再从这里进入审核。',
  'worldModel.atlas.assist.failedTitle': '这次同步没有完成',
  'worldModel.atlas.assist.failedDescription': '先重试提取或重新生成；如果只是继续研究，可以留在当前工作台。',
  'worldModel.atlas.assist.syncedTitle': '当前没有新的待审核草稿',
  'worldModel.atlas.assist.syncedDescription': '继续研究、补充输入，或留在当前 tab 深入治理。',
  'worldModel.atlas.assist.runningState': '处理中',
  'worldModel.atlas.assist.failedState': '失败',
  'worldModel.atlas.assist.reviewState': '待审核',
  'worldModel.atlas.assist.successState': '已同步',
  'worldModel.atlas.assist.openReview': '去审核',
  'worldModel.atlas.assist.attention.eyebrow': '治理注意',
  'worldModel.atlas.assist.attention.runningTitle': '世界治理同步仍在处理中',
  'worldModel.atlas.assist.attention.runningDescription': '先看下面的治理入口状态；完成后再决定是否切进审核。',
  'worldModel.atlas.assist.attention.failedTitle': '这次治理同步中断了',
  'worldModel.atlas.assist.attention.failedDescription': '先在下面重试提取或重新生成，不要把问题埋在当前 tab 里。',
  'worldModel.atlas.assist.attention.reviewTitle': 'Atlas 里已经积累了新的待审核草稿',
  'worldModel.atlas.assist.attention.reviewDescription': ({ count }: UiMessageParams) => `${String(count ?? 0)} 条草稿已经准备好，现在更适合先进入审核。`,
  'worldModel.atlas.assist.attention.showSection': '查看入口',
  'worldModel.atlas.assist.worldSummary': ({ entityCount, systemCount }: UiMessageParams) => `当前世界：${String(entityCount ?? 0)} 个实体 · ${String(systemCount ?? 0)} 个体系`,

  'worldModel.entity.new': '+ 新实体',
  'worldModel.entity.defaultName': '新实体',
  'worldModel.entity.empty': '选择一个实体查看详情',
  'worldModel.entity.delete': '删除实体',
  'worldModel.entity.deleteConfirm': '确定要删除这个实体吗？删除后无法恢复。',
  'worldModel.entity.description': '描述',
  'worldModel.entity.aliases': '别名',
  'worldModel.entity.noAliases': '（暂无别名）',
  'worldModel.entity.addAliasPlaceholder': '添加别名...',
  'worldModel.entity.addAlias': '添加',
  'worldModel.entity.attributes': '属性',
  'worldModel.entity.addAttribute': '+ 添加属性',
  'worldModel.entity.column.name': '属性名',
  'worldModel.entity.column.surface': '表层',
  'worldModel.entity.column.truth': '真相',
  'worldModel.entity.column.visibility': '可见',
  'worldModel.entity.customTypePlaceholder': '自定义类型...',
  'worldModel.attribute.reorder': '拖动排序',
  'worldModel.attribute.delete': '删除属性',
  'worldModel.entity.aiEnrich': 'AI 补完',

  'worldModel.relationship.empty': '选择一个实体查看关系',
  'worldModel.relationship.new': '创建关系',
  'worldModel.relationship.fromTo': ({ source, target }) => `从 ${String(source ?? '')} 到 ${String(target ?? '')}`,
  'worldModel.relationship.selectTargetFallback': '（请选择目标实体）',
  'worldModel.relationship.searchTargetPlaceholder': '搜索目标实体...',
  'worldModel.relationship.noMatchingTargets': '没有匹配的目标实体',
  'worldModel.relationship.labelPlaceholder': '关系标签',
  'worldModel.relationship.delete': '删除关系',
  'worldModel.relationship.deleteConfirm': '确定要删除这个关系吗？',
  'worldModel.relationship.description': '关系描述',
  'worldModel.relationship.descriptionPlaceholder': '（添加关系描述，决定续写质量）',
  'worldModel.relationship.inspectorEmpty': '点击一条关系查看描述',
  'worldModel.relationship.inspectorHint': '选择一条关系后，这里会展示其描述（更影响续写质量）',
  'worldModel.relationship.sidebarTitle': '关系',
  'worldModel.relationship.sidebarDraftCount': ({ count }) => `草稿 ${String(count ?? 0)}`,
  'worldModel.relationship.aiSuggestions': 'AI 建议',

  'worldModel.system.new': '+ 新体系',
  'worldModel.system.back': '‹ 世界体系',
  'worldModel.system.delete': '删除体系',
  'worldModel.system.deleteConfirm': '确认删除？',
  'worldModel.system.searchPlaceholder': '搜索体系...',
  'worldModel.system.namePlaceholder': '体系名称',
  'worldModel.system.constraints': '规则约束',
  'worldModel.system.addConstraint': '+ 添加约束',
  'worldModel.system.addRoot': '+ 添加根节点',
  'worldModel.system.addEvent': '+ 添加事件',
  'worldModel.system.addItem': '+ 添加规则',
  'worldModel.system.insert': '+ 插入',
  'worldModel.system.unsupportedType': '当前体系类型无法编辑，请检查数据是否已经迁移。',
  'worldModel.system.rejectAllTitle': '拒绝全部草稿体系？',
  'worldModel.system.rejectAllDescription': ({ count }) => `将删除 ${String(count ?? 0)} 个草稿体系。\n此操作不可撤销。`,
  'worldModel.system.rejectAllConfirm': '拒绝并删除',
  'worldModel.system.display.hierarchy': '层级结构',
  'worldModel.system.display.timeline': '时间线',
  'worldModel.system.display.list': '列表',
  'worldModel.system.display.graph': '关系图（只读）',

  'worldModel.legacyGraph.notice': '这是旧版关系图体系。当前版本仅保留读取兼容，不再支持新建或编辑图结构；如需继续维护，请迁移到关系或列表/层级体系。',
  'worldModel.legacyGraph.nodes': ({ count }) => `节点 (${String(count ?? 0)})`,
  'worldModel.legacyGraph.edges': ({ count }) => `连线 (${String(count ?? 0)})`,
  'worldModel.legacyGraph.emptyNodes': '没有可展示的节点。',
  'worldModel.legacyGraph.emptyEdges': '没有可展示的连线。',

  'worldModel.bootstrap.extractFromChapters': '从章节提取',
  'worldModel.bootstrap.reextractDrafts': '重新提取草稿',
  'worldModel.bootstrap.failed': '执行失败',
  'worldModel.bootstrap.completedIndexRefresh': '全书检索已更新',
  'worldModel.bootstrap.summaryCounts': ({ entities, relationships }) => `${String(entities ?? 0)} 实体 · ${String(relationships ?? 0)} 关系`,
  'worldModel.bootstrap.completedExtraction': ({ entities, relationships }) => `提取到 ${String(entities ?? 0)} 个实体、${String(relationships ?? 0)} 条关系`,
  'worldModel.bootstrap.confirmTitle': '危险操作：重新提取章节草稿',
  'worldModel.bootstrap.confirmDescription': '替换当前从章节提取的草稿（保留已确认内容），然后重新提取实体和关系。\n确认继续吗？',
  'worldModel.bootstrap.confirmAction': '确认重新提取',
  'worldModel.bootstrap.step.pending': '准备中',
  'worldModel.bootstrap.step.tokenizing': '分词处理',
  'worldModel.bootstrap.step.extracting': '提取候选词',
  'worldModel.bootstrap.step.windowing': '分析章节关联',
  'worldModel.bootstrap.step.refining': 'AI 精炼提取',
  'worldModel.bootstrap.noText': '请先上传章节内容',
  'worldModel.bootstrap.alreadyFresh': '全书检索已经是最新状态',
  'worldModel.bootstrap.triggerFailed': '操作失败，请重试',

  'worldModel.windowIndex.bootstrap.preparingContent': '正在准备全书内容',
  'worldModel.windowIndex.bootstrap.organizingChapters': '正在整理章节内容',
  'worldModel.windowIndex.bootstrap.ready': '已可从全书中查找线索',
  'worldModel.windowIndex.bootstrap.pendingSync': '章节更新后待同步',
  'worldModel.windowIndex.bootstrap.missing': '还在准备全书内容',
  'worldModel.windowIndex.bootstrap.failed': '全书检索暂不可用',
  'worldModel.windowIndex.copilot.preparingContent': '正在准备全书内容。',
  'worldModel.windowIndex.copilot.organizingContent': '章节有更新，正在整理全书内容；当前会先参考最近几章。',
  'worldModel.windowIndex.copilot.ready': '已可直接跨章节查找设定、人物与线索。',
  'worldModel.windowIndex.copilot.pendingSync': '章节有更新，正在同步全书内容；当前会先参考最近几章。',
  'worldModel.windowIndex.copilot.missing': '全书内容还在准备中；当前会先参考最近几章。',
  'worldModel.windowIndex.copilot.failed': '全书内容暂时整理失败；当前会先参考最近几章。',

  'worldModel.generate.title': '从设定生成',
  'worldModel.generate.description': '粘贴世界观设定文本，生成草稿后进入「草稿审核」确认。',
  'worldModel.generate.placeholder': '在这里粘贴世界观设定（例如：世界规则、阵营、人物关系、力量体系…）',
  'worldModel.generate.minLength': ({ count }) => `至少 ${String(count ?? 0)} 个非空白字符`,
  'worldModel.generate.tooLong': '已超过上限',
  'worldModel.generate.submit': '生成',
  'worldModel.generate.submitting': '生成中...',
  'worldModel.generate.importLink': '已有世界观文件？直接导入',
  'worldModel.generate.importing': '导入中...',
  'worldModel.generate.inputInvalid': '输入不符合要求，请检查长度',
  'worldModel.generate.serviceUnavailable': 'AI 服务不可用，请检查模型配置或稍后重试',
  'worldModel.generate.schemaInvalid': 'AI 输出解析失败，请重试',
  'worldModel.generate.conflict': '生成冲突，请稍后重试',
  'worldModel.generate.failed': '生成失败，请重试',
  'worldModel.generate.fileUnsupported': '文件格式不支持，请使用正确的世界观文件',
  'worldModel.generate.fileUnreadable': '文件内容无法识别，请检查文件格式',
  'worldModel.generate.validation.maxChars': ({ count }) => `最多输入 ${String(count ?? 0)} 个字符`,
  'worldModel.generate.validation.minChars': ({ count }) => `请至少输入 ${String(count ?? 0)} 个非空白字符`,
  'worldEntry.summary.generated': ({ entityCount, relationshipCount, systemCount }: UiMessageParams) =>
    `生成结果：${String(entityCount ?? 0)} 实体 · ${String(relationshipCount ?? 0)} 关系 · ${String(systemCount ?? 0)} 体系`,

  'worldModel.worldpack.title': '导入世界观',
  'worldModel.worldpack.subtitle': '上传世界观文件',
  'worldModel.worldpack.selectAndImport': '选择文件并导入',
  'worldModel.worldpack.import': '导入',
  'worldModel.worldpack.importing': '正在导入...',
  'worldModel.worldpack.completed': '世界观导入完成',
  'worldModel.worldpack.failed': '世界观导入失败，请重试',
  'worldModel.worldpack.fileUnsupported': '文件格式不支持，请使用正确的世界观文件',
  'worldModel.worldpack.fileUnreadable': '文件内容无法识别，请检查文件格式',

  'worldModel.draftReview.noMatches': '没有匹配项',
  'worldModel.draftReview.noDrafts': '暂无草稿',
  'worldModel.draftReview.viewAll': '查看全部 →',
  'worldModel.draftReview.aiCleanup': 'AI 整理',
  'worldModel.draftReview.rejectAndDelete': '拒绝并删除',
  'worldModel.draftReview.rejectAllTitle': ({ kind }) => `拒绝全部${String(kind ?? '')}？`,
  'worldModel.draftReview.rejectAllDescription': ({ count, kind }) => `将删除 ${String(count ?? 0)} 个草稿${String(kind ?? '')}。\n此操作不可撤销。`,

  'worldModel.onboarding.title': '先构建世界观，再开始写作',
  'worldModel.onboarding.description': '你可以从设定文本生成草稿，或从章节中自动提取实体与关系。',
  'worldModel.onboarding.generateTitle': '从设定生成',
  'worldModel.onboarding.generateDescription': '粘贴世界观设定，让 AI 提取实体、关系与体系草稿，然后你再逐条确认。',
  'worldModel.onboarding.extractTitle': '从章节提取',
  'worldModel.onboarding.extractDescription': '从已上传的章节内容中自动提取实体与关系草稿。',
  'worldModel.onboarding.extractUnavailable': '请先上传章节内容，提取才能运行。',
  'worldModel.onboarding.dismiss': '前往世界模型页稍后添加 →',
  'studio.preparation.title': '正在准备这部作品',
  'studio.preparation.uploadDescription': '我们正在导入章节内容。导入完成后，NovWr 会自动提取实体与关系；请先不要进行其他操作。',
  'studio.preparation.bootstrapDescription': '章节已经导入完成，正在自动提取实体与关系。请稍候。',
  'studio.preparation.failedTitle': '自动提取没有完成',
  'studio.preparation.failedDescription': '章节已经导入，但自动提取实体与关系失败了。你可以立即重试，或稍后再处理。',
  'studio.preparation.retry': '重新提取',
  'studio.preparation.defer': '稍后处理',
  'studio.preparation.stage.accepted': '上传已接收，正在排队导入',
  'studio.preparation.stage.decoding': '正在读取上传文件',
  'studio.preparation.stage.parsing': '正在识别章节结构',
  'studio.preparation.stage.planning': '正在规划后台任务',
  'studio.preparation.stage.persisting': '正在写入章节内容',
  'studio.preparation.stage.completed': '导入完成',
  'studio.preparation.stage.failed': '导入失败',
  'studio.demoGuide.eyebrow': 'Demo-first onboarding',
  'studio.demoGuide.title': '先按引导走一遍写作闭环，再导入你自己的正文',
  'studio.demoGuide.description': '这部示例项目用来讲清楚 NovWr 的工作方式：先看世界模型，再回到 Studio 找到续写断点，最后用全书检索和 Copilot 做补充判断。',
  'studio.demoGuide.completedTitle': '你已经跑通这部示例的写作闭环',
  'studio.demoGuide.completedDescription': '示例引导会自动收起；如果你想再看一遍每个入口，随时可以重新打开。',
  'studio.demoGuide.skippedTitle': '你已暂时收起这份示例引导',
  'studio.demoGuide.skippedDescription': '右侧会保留一个轻量入口；你想重新查看时，随时可以把它展开。',
  'studio.demoGuide.progress': ({ current, total }) => `进度 ${String(current ?? 0)}/${String(total ?? 4)}`,
  'studio.demoGuide.summaryChapters': ({ count }) => `${String(count ?? 0)} 章样例内容`,
  'studio.demoGuide.summaryWorld': ({ entityCount, systemCount }) => `${String(entityCount ?? 0)} 个实体 · ${String(systemCount ?? 0)} 个体系`,
  'studio.demoGuide.summaryLatest': ({ chapter }) => `续写断点：${String(chapter ?? '')}`,
  'studio.demoGuide.summaryLatestFallback': '续写断点待补充',
  'studio.demoGuide.chapterTitle': '先在 Studio 读一遍样例',
  'studio.demoGuide.chapterDescription': '先看章节结构、当前段落和保存后的呈现方式，再决定要不要开始第一次续写。',
  'studio.demoGuide.chapterAction': '打开当前样例章节',
  'studio.demoGuide.worldModelTitle': '先看世界模型',
  'studio.demoGuide.worldModelDescription': '在 Atlas 里浏览实体、关系和体系，理解这部样例是如何把设定组织成可检索结构的。',
  'studio.demoGuide.worldModelAction': '打开 Atlas 世界模型',
  'studio.demoGuide.breakpointTitle': '从单一断点开始第一次续写',
  'studio.demoGuide.breakpointDescription': ({ chapter }) => `把「${String(chapter ?? '')}」当作第一处续写断点，直接进入写作台试跑一次。`,
  'studio.demoGuide.breakpointDescriptionFallback': '示例断点暂未补充，先浏览世界模型与章节结构。',
  'studio.demoGuide.breakpointAction': '打开续写台',
  'studio.demoGuide.copilotTitle': '再用 Novel Copilot 看全书线索',
  'studio.demoGuide.copilotDescription': '需要跨章节核查人物、设定或伏笔时，再打开 Copilot 看它如何利用全书检索辅助判断。',
  'studio.demoGuide.copilotAction': '打开 Novel Copilot',
  'studio.demoGuide.windowIndexLabel': 'Window Index：',
  'studio.demoGuide.complete': '已完成',
  'studio.demoGuide.autoHideHint': '走完全部步骤后，引导会自动收起；如果你想直接略过，也可以现在跳过。',
  'studio.demoGuide.skip': '跳过引导',
  'studio.demoGuide.reopen': '查看 Demo 引导',

  'worldModel.placeholder.key': '键名',
  'worldModel.placeholder.value': '值',
  'worldModel.placeholder.name': '名称',
  'worldModel.placeholder.description': '描述',
  'worldModel.placeholder.nodeName': '节点名称',
  'worldModel.placeholder.eventName': '事件名称',
  'worldModel.placeholder.time': '时间',
  'worldModel.placeholder.constraint': '约束规则',
  'worldModel.placeholder.systemName': '体系名称',

  'worldModel.error.deleteFailed': '删除失败，请重试',
  'worldModel.error.saveFailed': '保存失败，请重试',
  'worldModel.error.confirmFailed': '确认失败，请重试',
  'worldModel.error.rejectFailed': '拒绝失败，请重试',
  'worldModel.error.bootstrapTriggerFailed': '操作失败，请重试',

  'chapter.loadingContent': '加载章节内容...',
  'chapter.emptySelectToRead': '选择一个章节开始阅读',

  'worldpack.import.warning.ambiguous_alias': ({ alias, entity_keys }) =>
    `别名“${String(alias ?? '')}”同时指向多个实体：${String(entity_keys ?? '')}` ,
  'worldpack.import.warning.entity_missing_name': ({ key }) =>
    `实体“${String(key ?? '')}”缺少名称，已跳过`,
  'worldpack.import.warning.entity_missing_name_preserve_existing': ({ key }) =>
    `实体“${String(key ?? '')}”缺少名称；为关系解析保留了现有行`,
  'worldpack.import.warning.entity_name_conflict': ({ name }) =>
    `实体名“${String(name ?? '')}”已存在且绑定到其他 worldpack 身份，已跳过`,
  'worldpack.import.warning.entity_linked_by_name': ({ key, name }) =>
    `实体“${String(key ?? '')}”已按名称“${String(name ?? '')}”关联到现有行`,
  'worldpack.import.warning.relationship_missing_label': '关系缺少标签，已跳过',
  'worldpack.import.warning.relationship_missing_refs': ({ source_key, target_key }) =>
    `关系缺少引用：source_key='${String(source_key ?? '')}'，target_key='${String(target_key ?? '')}'`,
  'worldpack.import.warning.system_missing_name': '体系缺少名称，已跳过',
  'worldpack.import.warning.system_name_conflict': ({ name }) =>
    `体系名“${String(name ?? '')}”已被其他包占用，已跳过`,
  'worldpack.import.warning.skip_delete_promoted_entity': ({ key }) =>
    `实体“${String(key ?? '')}”存在非 worldpack 依赖，已保留`,
  'worldpack.import.warning.preserved_entities_skipped': ({ count, sample }) =>
    `跳过覆盖 ${String(count ?? 0)} 个受保护实体：${String(sample ?? '')}`,
  'worldpack.import.warning.preserved_attributes_skipped': ({ count, sample, more_entities_count }) =>
    `跳过覆盖 ${String(count ?? 0)} 个受保护属性：${String(sample ?? '')}${
      Number(more_entities_count ?? 0) > 0 ? ` (+${String(more_entities_count ?? 0)} more entities)` : ''
    }`,
  'worldpack.import.warning.preserved_relationships_skipped': ({ count, sample }) =>
    `跳过覆盖 ${String(count ?? 0)} 条受保护关系：${String(sample ?? '')}`,
  'worldpack.import.warning.preserved_systems_skipped': ({ count, sample }) =>
    `跳过覆盖 ${String(count ?? 0)} 个受保护体系：${String(sample ?? '')}`,
  'worldpack.import.warning.duplicate_entity_key': ({ key }) =>
    `payload 中存在重复实体 key“${String(key ?? '')}”，已跳过`,

  'world.generate.warning.system_item_missing_time': '时间线条目缺少时间，已跳过',
  'world.generate.warning.system_display_type_conflict': ({ name, downgraded_display_type }) =>
    `体系“${String(name ?? '')}”在分块间结构类型冲突，已降级为 ${String(downgraded_display_type ?? '')}`,
  'world.generate.warning.entity_missing_name': '实体名称为空，已跳过',
  'world.generate.warning.relationship_missing_fields': '关系缺少 source/target/label，已跳过',
  'world.generate.warning.relationship_unknown_entity': ({ source, target }) =>
    `关系引用了未知实体，已丢弃（${String(source ?? '')} -> ${String(target ?? '')}）`,
  'world.generate.warning.relationship_self_reference': ({ entity }) =>
    `关系的 source 与 target 相同，已跳过（${String(entity ?? '')}）`,
  'world.generate.warning.relationship_duplicate': ({ label }) =>
    `重复关系已丢弃（${String(label ?? '')}）`,
  'world.generate.warning.system_missing_name': '体系名称为空，已跳过',
  'world.generate.warning.system_duplicate': ({ name }) =>
    `重复体系名已丢弃（${String(name ?? '')}）`,
  'world.generate.warning.system_name_conflict': ({ name }) =>
    `体系名已存在，已跳过（${String(name ?? '')}）`,

  'continuation.prosecheck.warning.repeated_ngram': ({ phrase, count }) =>
    `检测到重复短语“${String(phrase ?? '')}”（出现 ${String(count ?? 0)} 次）`,
  'continuation.prosecheck.warning.long_paragraph': ({ length, unit }) =>
    `段落偏长（约 ${String(length ?? 0)} ${String(unit ?? '') === 'words' ? '词' : '字'}）`,
  'continuation.prosecheck.warning.abnormal_sentence_length': ({ length, unit }) =>
    `句子偏长（约 ${String(length ?? 0)} ${String(unit ?? '') === 'words' ? '词' : '字'}）`,
  'continuation.prosecheck.warning.summary_tone': ({ phrase }) =>
    `检测到总结/分析式表达“${String(phrase ?? '')}”，可能不适合正文叙事`,
} as const satisfies Record<string, UiMessageValue>

export const continuationZhMessages = {
  // -- Continuation Setup Stage --
  'continuation.setup.basedOn': ({ chapter }: UiMessageParams) => `基于${String(chapter ?? '')}继续`,
  'continuation.setup.charCount': ({ count }: UiMessageParams) => `${String(count ?? 0)} 字`,
  'continuation.setup.loadingChapter': '加载章节内容...',
  'continuation.setup.emptyChapter': '章节暂无内容',
  'continuation.setup.title': '续写设置',
  'continuation.setup.instruction': '续写指令（可选）',
  'continuation.setup.instructionPlaceholder': '描述你想要的情节走向，或留空让 AI 自由续写',
  'continuation.setup.length': '续写长度',
  'continuation.setup.advancedSettings': '高级设置',
  'continuation.setup.contextChapters': '上下文章节数',
  'continuation.setup.numVersions': '生成版本数',
  'continuation.setup.temperature': '创意温度',
  'continuation.setup.generate': '生成续写',

  // -- Continuation Results Stage --
  'continuation.results.loading': '正在加载续写结果...',
  'continuation.results.retry': '重试',
  'continuation.results.back': '返回',
  'continuation.results.noResults': '未找到续写结果，请从工作区重新生成。',
  'continuation.results.returnToWorkspace': '返回工作区',
  'continuation.results.quotaExhausted': '生成额度已用完',
  'continuation.results.serviceBusy': '当前使用人数较多，请稍后再试',
  'continuation.results.alreadyRunning': '这次续写已经在处理中，请等待当前结果返回',
  'continuation.results.requestFailed': ({ status }: UiMessageParams) => `请求失败（HTTP ${String(status ?? '')})`,
  'continuation.results.streamFallbackNotice': '当前网络不适合实时流式输出，已自动切换到稳定返回模式。',
  'continuation.results.quotaFeedback': '提交使用反馈即可获得额外生成额度，立即继续创作。',
  'continuation.results.submitFeedbackUnlock': '提交反馈，解锁额度',
  'continuation.results.feedbackAlreadyClaimed': '反馈额度已领取。你可以在设置中配置自己的 API Key 继续使用。',
  'continuation.results.goToSettings': '前往设置',
  'continuation.results.badge': '续写结果',
  'continuation.results.continuationOf': ({ chapter }: UiMessageParams) => `${String(chapter ?? '')}续写`,
  'continuation.results.generating': '生成中',
  'continuation.results.adopt': '采纳此版本',
  'continuation.results.regenerate': '重新生成',
  'continuation.results.exportAll': '导出全部',
  'continuation.results.version': ({ n }: UiMessageParams) => `版本 ${String(n ?? '')}`,
  'continuation.results.injectionSummary': ({ entities, relationships, systems }: UiMessageParams) =>
    `注入摘要(${String(entities ?? 0)} 个实体,${String(relationships ?? 0)} 个关系,${String(systems ?? 0)} 个系统)`,
  'continuation.results.emptyContent': '暂无内容',
  'continuation.results.exportVersionHeader': ({ n }: UiMessageParams) => `========== 版本 ${String(n ?? '')} ==========`,

  // -- Chapter Editor --
  'editor.undo': '撤销',
  'editor.redo': '重做',
  'editor.driftWarning': '漂移警告',
  'editor.charCount': ({ count }: UiMessageParams) => `${String(count ?? 0)} 字`,
  'editor.cursorPosition': ({ para, col }: UiMessageParams) => `第 ${String(para ?? 0)} 段 · 第 ${String(col ?? 0)} 列`,
  'editor.autoSaved': '已自动保存',
  'editor.unsaved': '未保存更改',
  'editor.save': '保存',

  // -- Drift Warning Popover --
  'drift.unknownTerm': '未知名词',
  'drift.unknownNaming': '未知称谓',
  'drift.unknownDefault': '未知词汇',
  'drift.dismiss': '忽略',

  // -- Prose Warnings Panel --
  'prose.repeatedNgram': '重复短语',
  'prose.longParagraph': '段落过长',
  'prose.abnormalSentenceLength': '句子过长',
  'prose.summaryTone': '总结式语气',
  'prose.checkTitle': ({ count }: UiMessageParams) => `文本质量检查（${String(count ?? 0)} 项提示）`,
  'prose.itemCount': ({ count }: UiMessageParams) => `${String(count ?? 0)} 项`,
  'prose.candidate': ({ n }: UiMessageParams) => `候选 ${String(n ?? '')}`,

  // -- Studio Page (continuation-path strings) --
  'studio.chapter.deleteConfirm': ({ chapter }: UiMessageParams) => `确定要删除${String(chapter ?? '')}吗？此操作无法撤销。`,
  'studio.chapter.editing': '编辑中',
  'studio.chapter.reading': '阅读中',
  'studio.chapter.titlePlaceholder': '输入章节标题',
  'studio.chapter.titleEditHint': '双击编辑标题',
  'studio.chapter.titleAddHint': '双击添加标题',
  'studio.header.workspace': '章节工作台',
  'studio.header.selectChapter': '选择章节',
  'studio.actions.moreActions': '更多操作',
  'studio.actions.exportAllChapters': '导出全部章节',
  'studio.loading': '加载中...',
  'studio.novelNotFound': '作品不存在',
  'studio.chapter.charCount': ({ count }: UiMessageParams) => `${String(count ?? 0)} 字`,
  'studio.chapter.updated': ({ time }: UiMessageParams) => `${String(time ?? '')}更新`,
  'studio.chapter.edit': '编辑',
  'studio.chapter.delete': '删除章节',
  'studio.rail.workspace': '工作区',
  'studio.rail.continuationTitle': '续写设置',
  'studio.rail.continuationDescription': ({ chapter }: UiMessageParams) => `基于${String(chapter ?? '')}配置下一次续写`,
  'studio.rail.atlasTitle': 'Atlas 世界模型',
  'studio.rail.atlasDescription': '进入关系图谱、审核与深度整理',
  'studio.rail.searchChapters': '搜索章节...',
  'studio.rail.searchResults': ({ count }: UiMessageParams) => `搜索结果：${String(count ?? 0)} 项`,
  'studio.rail.chapters': '章节',
  'studio.rail.createChapter': '新建章节',
  'studio.rail.noChapters': '暂无章节',
  'studio.rail.chapterCount': ({ count }: UiMessageParams) => `共 ${String(count ?? 0)} 章`,
  'studio.stage.returnToResults': '返回结果',
  'studio.stage.openInAtlas': '在 Atlas 中打开',
  'studio.stage.entity.title': '实体检查',
  'studio.stage.entity.description': '查看并轻量编辑当前上下文关联的实体；复杂结构治理仍留给 Atlas。',
  'studio.stage.entity.openCopilot': '实体 Copilot',
  'studio.stage.relationship.title': '关系检查',
  'studio.stage.relationship.currentEntity': '当前实体',
  'studio.stage.relationship.description': ({ subject }: UiMessageParams) => `围绕 ${String(subject ?? '')} 轻量检查关系描述、一致性与草稿确认；图谱与拓扑修改仍留在 Atlas。`,
  'studio.stage.relationship.openCopilot': '关系 Copilot',
  'studio.stage.relationship.noContext': '未找到可检查的实体上下文。',
  'studio.stage.relationship.entityWithId': ({ id }: UiMessageParams) => `实体 ${String(id ?? '')}`,
  'studio.stage.relationship.forEntity': ({ subject }: UiMessageParams) => `${String(subject ?? '')} 的关系`,
  'studio.stage.relationship.count': ({ count }: UiMessageParams) => `共 ${String(count ?? 0)} 条关系`,
  'studio.stage.relationship.empty': '暂无关系',
  'studio.stage.relationship.unnamed': '未命名关系',
  'studio.stage.draftReview.title': '草稿审核',
  'studio.stage.draftReview.description': '在写作上下文中快速处理单项草稿；批量治理和更高密度工作交给 Atlas。',
  'studio.stage.system.title': '体系检查',
  'studio.stage.system.description': '在写作上下文中检查体系描述与可见性；结构编辑、约束维护和更高密度治理仍留给 Atlas。',
  'studio.stage.system.sidebarTitle': '世界体系',
  'studio.stage.system.count': ({ count }: UiMessageParams) => `共 ${String(count ?? 0)} 个体系`,
  'studio.stage.system.empty': '暂无体系',
  'studio.stage.system.unnamed': '未命名体系',
  'studio.stage.system.selectPrompt': '选择一个体系开始检查。',
  'studio.stage.system.confirm': '确认体系',
  'studio.stage.system.help': 'Studio 只处理体系的轻量检查与元信息编辑；约束、层级/时间线/列表结构等深度编辑请转到 Atlas。',
  'studio.stage.system.descriptionSection': '描述',
  'studio.stage.system.summary.legacyGraph': '旧图谱类型，仅在 Atlas 中提供完整只读查看。',
  'studio.stage.system.summary.hierarchy': ({ count }: UiMessageParams) => `层级节点 ${String(count ?? 0)} 个`,
  'studio.stage.system.summary.timeline': ({ count }: UiMessageParams) => `时间节点 ${String(count ?? 0)} 个`,
  'studio.stage.system.summary.list': ({ count }: UiMessageParams) => `列表规则 ${String(count ?? 0)} 条`,
  'studio.assistant.toggleSidebar': '切换 AI 侧栏',
  'studio.research.eyebrow': '研究入口',
  'studio.research.title': '先研究，再决定是否进入治理',
  'studio.research.description': '跨章节核查人物、设定缺口和关键线索时，从这里打开 Novel Copilot 的全书研究。',
  'studio.research.openWholeBook': '打开全书研究',
  'studio.research.openWholeBookHint': '检索全书线索、设定缺口与值得继续追踪的世界锚点。',
  'studio.research.contextualEyebrow': '当前上下文',
  'studio.worldEntry.eyebrow': '世界入口',
  'studio.worldEntry.title': '把世界构建工作送去 Atlas',
  'studio.worldEntry.reviewHint': '生成和提取只负责把草稿送入 Atlas，正式审阅与治理仍在 Atlas 中完成。',
  'studio.worldEntry.summary': ({ entityCount, systemCount }: UiMessageParams) => `当前世界：${String(entityCount ?? 0)} 个实体 · ${String(systemCount ?? 0)} 个体系`,
  'studio.worldEntry.summaryEmpty': '当前还没有实体或体系草稿',
  'studio.worldEntry.attention.eyebrow': 'Atlas 交接',
  'studio.worldEntry.attention.runningTitle': '世界同步仍在处理中',
  'studio.worldEntry.attention.runningDescription': '先确认下面的世界入口状态；完成后再决定是否进入 Atlas。',
  'studio.worldEntry.attention.failedTitle': '这次世界同步中断了',
  'studio.worldEntry.attention.failedDescription': '先在下面继续处理或重试提取，再决定是否切去 Atlas。',
  'studio.worldEntry.attention.reviewTitle': 'Atlas 里已经有新的草稿待审核',
  'studio.worldEntry.attention.reviewDescription': '这批世界草稿已经准备好了，现在更适合先进入审核，而不是继续忽略它。',
  'studio.worldEntry.attention.showPanel': '查看入口',
  'studio.worldEntry.handoff.reviewReadyTitle': '草稿已送到 Atlas，下一步去审核',
  'studio.worldEntry.handoff.reviewReadyDescription': 'Studio 只负责发起；正式审阅与治理仍在 Atlas 中完成。',
  'studio.worldEntry.handoff.syncCompleteTitle': '同步已完成',
  'studio.worldEntry.handoff.syncCompleteDescription': '这次没有强制跳转。你可以继续写作，或稍后再去 Atlas 查看。',
  'studio.worldEntry.handoff.extractRunningTitle': '正在从章节同步世界草稿',
  'studio.worldEntry.handoff.extractRunningDescription': '你可以继续留在 Studio；完成后再按需去 Atlas 审核。',
  'studio.worldEntry.handoff.extractFailedTitle': '章节提取没有完成',
  'studio.worldEntry.handoff.extractFailedDescription': '先重试提取；如果只是查看当前世界，也可以直接打开 Atlas。',
  'studio.worldEntry.handoff.openReview': '进入草稿审核',
  'studio.worldEntry.handoff.openAtlas': '打开 Atlas',
  'studio.worldEntry.handoff.runningState': '处理中',
  'studio.worldEntry.handoff.failedState': '失败',
  'studio.worldEntry.handoff.reviewState': '待审核',
  'studio.worldEntry.handoff.successState': '已同步',
  'studio.contextualCopilot.entity.title': '实体补完',
  'studio.contextualCopilot.entity.description': ({ subject }: UiMessageParams) => `围绕「${String(subject ?? '')}」继续补全设定、核查依据与属性。`,
  'studio.contextualCopilot.entity.descriptionFallback': '继续补全当前实体的设定与属性。',
  'studio.contextualCopilot.relationship.title': '关系补完',
  'studio.contextualCopilot.relationship.description': ({ subject }: UiMessageParams) => `围绕「${String(subject ?? '')}」的关系网络继续核查与补完。`,
  'studio.contextualCopilot.relationship.descriptionFallback': '继续核查当前实体相关的关系线索。',
  'studio.injectionSummary.title': ({ count }: UiMessageParams) => `注入摘要 · ${String(count ?? 0)} 个元素`,
  'studio.injectionSummary.empty': '无注入内容',
  'studio.injectionSummary.openInAtlas': '在 Atlas 中查看全部',
} as const satisfies Record<string, UiMessageValue>
export const novelZhMessages = {
  ...worldModelZhMessages,
  ...continuationZhMessages,
} as const satisfies Record<string, UiMessageValue>

export const novelEnMessages = {
  'worldModel.common.all': 'All',
  'worldModel.common.entities': 'Entities',
  'worldModel.common.relationships': 'Relationships',
  'worldModel.common.systems': 'Systems',
  'worldModel.common.draftReview': 'Draft review',
  'worldModel.common.statusDraft': 'Draft',
  'worldModel.common.statusConfirmed': 'Confirmed',
  'worldModel.common.view': 'View',
  'worldModel.common.locate': 'Locate',
  'worldModel.common.reject': 'Reject',
  'worldModel.common.retry': 'Retry',
  'worldModel.common.processing': 'Processing...',
  'worldModel.common.file': 'File',
  'worldModel.common.pack': 'Pack',
  'worldModel.common.notes': 'Notes',
  'worldModel.common.created': 'Created',
  'worldModel.common.updated': 'Updated',
  'worldModel.common.deleted': 'Deleted',
  'worldModel.common.none': 'None',
  'worldModel.common.remove': 'Remove',
  'worldModel.common.visibility': 'Visibility',
  'worldModel.common.description': 'Description',
  'worldModel.common.aliases': 'Aliases',
  'worldModel.common.visibilityActive': 'Active',
  'worldModel.common.visibilityReference': 'Reference',
  'worldModel.common.visibilityHidden': 'Hidden',
  'worldModel.common.unknownNode': 'Unknown node',
  'worldModel.common.unnamedNode': ({ index }) => `Unnamed node ${String(index ?? 0)}`,
  'worldModel.common.searchDrafts': 'Search drafts...',
  'worldModel.common.searchEntities': 'Search entities...',
  'worldModel.common.searchSystems': 'Search systems...',

  'worldModel.atlas.returnToStudio': 'Return to Studio',
  'worldModel.atlas.reviewTab': 'Draft review',
  'worldModel.atlas.startEditingSystem': 'Select a system to start editing',
  'worldModel.atlas.assist.eyebrow': 'Atlas assistant',
  'worldModel.atlas.assist.title': 'Check the world first, then handle drafts',
  'worldModel.atlas.assist.description': 'The left navigator only scans and selects; the right side is where Atlas handles research, sync, and review assist.',
  'worldModel.atlas.assist.researchEyebrow': 'Check lore',
  'worldModel.atlas.assist.wholeBookAction': 'Search the whole book',
  'worldModel.atlas.assist.contextEntityTitle': 'Check this entity',
  'worldModel.atlas.assist.contextEntityHint': 'Fill in this entity’s details, evidence, and possible relationships.',
  'worldModel.atlas.assist.contextRelationshipTitle': 'Check this relationship',
  'worldModel.atlas.assist.contextRelationshipHint': 'Review how the current entity connects to others and where conflicts may exist.',
  'worldModel.atlas.assist.contextReviewTitle': 'Triage drafts first',
  'worldModel.atlas.assist.contextReviewHint': 'Before batch review, check for naming drift, missing fields, and obvious conflicts.',
  'worldModel.atlas.assist.governanceEyebrow': 'Create and review',
  'worldModel.atlas.assist.queueTitle': 'Drafts waiting for review',
  'worldModel.atlas.assist.queueHint': ({ count }) => `${String(count ?? 0)} ${Number(count) === 1 ? 'draft is' : 'drafts are'} waiting for review`,
  'worldModel.atlas.assist.queueEmpty': 'No drafts are waiting for review',
  'worldModel.atlas.assist.reviewReadyTitle': 'Drafts are ready — move into review next',
  'worldModel.atlas.assist.reviewReadyDescription': 'Atlas already has the new governance intake; the next step is draft review, not lingering in the current list.',
  'worldModel.atlas.assist.runningTitle': 'World-governance intake is still syncing',
  'worldModel.atlas.assist.runningDescription': 'No forced tab switch is needed while it runs. Enter review from here once the sync finishes.',
  'worldModel.atlas.assist.failedTitle': 'This sync did not finish',
  'worldModel.atlas.assist.failedDescription': 'Retry extraction or generation first. If you only need more research, stay in the current workspace.',
  'worldModel.atlas.assist.syncedTitle': 'No new drafts are waiting for review',
  'worldModel.atlas.assist.syncedDescription': 'Keep researching, add more input, or stay in the current tab for deeper governance.',
  'worldModel.atlas.assist.runningState': 'Running',
  'worldModel.atlas.assist.failedState': 'Failed',
  'worldModel.atlas.assist.reviewState': 'Needs review',
  'worldModel.atlas.assist.successState': 'Synced',
  'worldModel.atlas.assist.openReview': 'Review now',
  'worldModel.atlas.assist.attention.eyebrow': 'Governance attention',
  'worldModel.atlas.assist.attention.runningTitle': 'World-governance sync is still running',
  'worldModel.atlas.assist.attention.runningDescription': 'Check the governance entry below first, then decide when review needs your focus.',
  'worldModel.atlas.assist.attention.failedTitle': 'This governance sync was interrupted',
  'worldModel.atlas.assist.attention.failedDescription': 'Retry extraction or generation below first instead of burying the issue under the current tab.',
  'worldModel.atlas.assist.attention.reviewTitle': 'Atlas already has new drafts waiting for review',
  'worldModel.atlas.assist.attention.reviewDescription': ({ count }) => `${String(count ?? 0)} ${Number(count) === 1 ? 'draft is' : 'drafts are'} ready, so review is the higher-priority next step.`,
  'worldModel.atlas.assist.attention.showSection': 'Show entry',
  'worldModel.atlas.assist.worldSummary': ({ entityCount, systemCount }) => `Current world: ${String(entityCount ?? 0)} ${Number(entityCount) === 1 ? 'entity' : 'entities'} · ${String(systemCount ?? 0)} ${Number(systemCount) === 1 ? 'system' : 'systems'}`,

  'worldModel.entity.new': '+ New entity',
  'worldModel.entity.defaultName': 'New entity',
  'worldModel.entity.empty': 'Select an entity to view details',
  'worldModel.entity.delete': 'Delete entity',
  'worldModel.entity.deleteConfirm': 'Delete this entity? This cannot be undone.',
  'worldModel.entity.description': 'Description',
  'worldModel.entity.aliases': 'Aliases',
  'worldModel.entity.noAliases': '(No aliases yet)',
  'worldModel.entity.addAliasPlaceholder': 'Add alias...',
  'worldModel.entity.addAlias': 'Add',
  'worldModel.entity.attributes': 'Attributes',
  'worldModel.entity.addAttribute': '+ Add attribute',
  'worldModel.entity.column.name': 'Attribute',
  'worldModel.entity.column.surface': 'Surface',
  'worldModel.entity.column.truth': 'Truth',
  'worldModel.entity.column.visibility': 'Visible',
  'worldModel.entity.customTypePlaceholder': 'Custom type...',
  'worldModel.attribute.reorder': 'Drag to reorder',
  'worldModel.attribute.delete': 'Delete attribute',
  'worldModel.entity.aiEnrich': 'AI enrich',

  'worldModel.relationship.empty': 'Select an entity to view relationships',
  'worldModel.relationship.new': 'Create relationship',
  'worldModel.relationship.fromTo': ({ source, target }) => `From ${String(source ?? '')} to ${String(target ?? '')}`,
  'worldModel.relationship.selectTargetFallback': '(select a target entity)',
  'worldModel.relationship.searchTargetPlaceholder': 'Search target entities...',
  'worldModel.relationship.noMatchingTargets': 'No matching target entities',
  'worldModel.relationship.labelPlaceholder': 'Relationship label',
  'worldModel.relationship.delete': 'Delete relationship',
  'worldModel.relationship.deleteConfirm': 'Delete this relationship?',
  'worldModel.relationship.description': 'Relationship description',
  'worldModel.relationship.descriptionPlaceholder': '(Add a relationship description to improve continuation quality)',
  'worldModel.relationship.inspectorEmpty': 'Select a relationship to view its description',
  'worldModel.relationship.inspectorHint': 'After you select a relationship, its description appears here and has a bigger impact on continuation quality',
  'worldModel.relationship.sidebarTitle': 'Relationships',
  'worldModel.relationship.sidebarDraftCount': ({ count }) => `Drafts ${String(count ?? 0)}`,
  'worldModel.relationship.aiSuggestions': 'AI suggestions',

  'worldModel.system.new': '+ New system',
  'worldModel.system.back': '‹ Systems',
  'worldModel.system.delete': 'Delete system',
  'worldModel.system.deleteConfirm': 'Confirm delete?',
  'worldModel.system.searchPlaceholder': 'Search systems...',
  'worldModel.system.namePlaceholder': 'System name',
  'worldModel.system.constraints': 'Constraints',
  'worldModel.system.addConstraint': '+ Add constraint',
  'worldModel.system.addRoot': '+ Add root node',
  'worldModel.system.addEvent': '+ Add event',
  'worldModel.system.addItem': '+ Add rule',
  'worldModel.system.insert': '+ Insert',
  'worldModel.system.unsupportedType': 'This system type cannot be edited right now. Check whether the data still needs migration.',
  'worldModel.system.rejectAllTitle': 'Reject all draft systems?',
  'worldModel.system.rejectAllDescription': ({ count }) => `This will delete ${String(count ?? 0)} draft systems.\nThis cannot be undone.`,
  'worldModel.system.rejectAllConfirm': 'Reject and delete',
  'worldModel.system.display.hierarchy': 'Hierarchy',
  'worldModel.system.display.timeline': 'Timeline',
  'worldModel.system.display.list': 'List',
  'worldModel.system.display.graph': 'Graph (read-only)',

  'worldModel.legacyGraph.notice': 'This is a legacy graph-based system. The current version keeps read compatibility only and no longer supports creating or editing graph structures. To keep maintaining it, migrate the data to relationships or to a list/hierarchy system.',
  'worldModel.legacyGraph.nodes': ({ count }) => `Nodes (${String(count ?? 0)})`,
  'worldModel.legacyGraph.edges': ({ count }) => `Edges (${String(count ?? 0)})`,
  'worldModel.legacyGraph.emptyNodes': 'No nodes to display.',
  'worldModel.legacyGraph.emptyEdges': 'No edges to display.',

  'worldModel.bootstrap.extractFromChapters': 'Extract from chapters',
  'worldModel.bootstrap.reextractDrafts': 'Re-extract drafts',
  'worldModel.bootstrap.failed': 'Run failed',
  'worldModel.bootstrap.completedIndexRefresh': 'Whole-book retrieval refreshed',
  'worldModel.bootstrap.summaryCounts': ({ entities, relationships }) => `${String(entities ?? 0)} entities · ${String(relationships ?? 0)} relationships`,
  'worldModel.bootstrap.completedExtraction': ({ entities, relationships }) => `Extracted ${String(entities ?? 0)} entities and ${String(relationships ?? 0)} relationships`,
  'worldModel.bootstrap.confirmTitle': 'Dangerous action: re-extract chapter drafts',
  'worldModel.bootstrap.confirmDescription': 'Replace the current drafts extracted from chapters (while keeping confirmed data), then extract entities and relationships again.\nContinue?',
  'worldModel.bootstrap.confirmAction': 'Confirm re-extract',
  'worldModel.bootstrap.step.pending': 'Preparing',
  'worldModel.bootstrap.step.tokenizing': 'Tokenizing',
  'worldModel.bootstrap.step.extracting': 'Extracting candidates',
  'worldModel.bootstrap.step.windowing': 'Analyzing chapter links',
  'worldModel.bootstrap.step.refining': 'Refining with AI',
  'worldModel.bootstrap.noText': 'Upload chapter content first',
  'worldModel.bootstrap.alreadyFresh': 'Whole-book retrieval is already up to date',
  'worldModel.bootstrap.triggerFailed': 'Action failed. Please try again.',

  'worldModel.windowIndex.bootstrap.preparingContent': 'Preparing whole-book content',
  'worldModel.windowIndex.bootstrap.organizingChapters': 'Organizing chapter content',
  'worldModel.windowIndex.bootstrap.ready': 'Ready to search clues across the whole book',
  'worldModel.windowIndex.bootstrap.pendingSync': 'Waiting to sync after chapter updates',
  'worldModel.windowIndex.bootstrap.missing': 'Whole-book content is still being prepared',
  'worldModel.windowIndex.bootstrap.failed': 'Whole-book retrieval is temporarily unavailable',
  'worldModel.windowIndex.copilot.preparingContent': 'Preparing whole-book content.',
  'worldModel.windowIndex.copilot.organizingContent': 'The chapters changed, so whole-book content is being organized; for now the app will fall back to recent chapters.',
  'worldModel.windowIndex.copilot.ready': 'Ready to search settings, characters, and clues across chapters.',
  'worldModel.windowIndex.copilot.pendingSync': 'The chapters changed, so whole-book content is syncing; for now the app will fall back to recent chapters.',
  'worldModel.windowIndex.copilot.missing': 'Whole-book content is still being prepared; for now the app will fall back to recent chapters.',
  'worldModel.windowIndex.copilot.failed': 'Whole-book content failed to organize for now; the app will fall back to recent chapters.',

  'worldModel.generate.title': 'Generate from setting text',
  'worldModel.generate.description': 'Paste world-setting text here, generate drafts, then review them in “Draft review”.',
  'worldModel.generate.placeholder': 'Paste world-setting text here (for example: world rules, factions, character relationships, power systems...)',
  'worldModel.generate.minLength': ({ count }) => `At least ${String(count ?? 0)} non-whitespace characters`,
  'worldModel.generate.tooLong': 'The input exceeds the limit',
  'worldModel.generate.submit': 'Generate',
  'worldModel.generate.submitting': 'Generating...',
  'worldModel.generate.importLink': 'Already have a worldpack file? Import it directly',
  'worldModel.generate.importing': 'Importing...',
  'worldModel.generate.inputInvalid': 'The input is invalid. Please check the length.',
  'worldModel.generate.serviceUnavailable': 'The AI service is unavailable. Check the model config or try again later.',
  'worldModel.generate.schemaInvalid': 'The AI response could not be parsed. Please try again.',
  'worldModel.generate.conflict': 'The generation conflicted with another change. Please try again.',
  'worldModel.generate.failed': 'Generation failed. Please try again.',
  'worldModel.generate.fileUnsupported': 'Unsupported file format. Please use a valid worldpack file.',
  'worldModel.generate.fileUnreadable': 'The file content could not be recognized. Please check the file format.',
  'worldModel.generate.validation.maxChars': ({ count }) => `At most ${String(count ?? 0)} characters`,
  'worldModel.generate.validation.minChars': ({ count }) => `Please enter at least ${String(count ?? 0)} non-whitespace characters`,
  'worldEntry.summary.generated': ({ entityCount, relationshipCount, systemCount }) =>
    `Generated: ${String(entityCount ?? 0)} ${Number(entityCount) === 1 ? 'entity' : 'entities'} · ${String(relationshipCount ?? 0)} ${Number(relationshipCount) === 1 ? 'relationship' : 'relationships'} · ${String(systemCount ?? 0)} ${Number(systemCount) === 1 ? 'system' : 'systems'}`,

  'worldModel.worldpack.title': 'Import worldpack',
  'worldModel.worldpack.subtitle': 'Upload a worldpack file',
  'worldModel.worldpack.selectAndImport': 'Choose a file and import',
  'worldModel.worldpack.import': 'Import',
  'worldModel.worldpack.importing': 'Importing...',
  'worldModel.worldpack.completed': 'Worldpack import completed',
  'worldModel.worldpack.failed': 'Worldpack import failed. Please try again.',
  'worldModel.worldpack.fileUnsupported': 'Unsupported file format. Please use a valid worldpack file.',
  'worldModel.worldpack.fileUnreadable': 'The file content could not be recognized. Please check the file format.',

  'worldModel.draftReview.noMatches': 'No matching items',
  'worldModel.draftReview.noDrafts': 'No drafts yet',
  'worldModel.draftReview.viewAll': 'View all →',
  'worldModel.draftReview.aiCleanup': 'AI cleanup',
  'worldModel.draftReview.rejectAndDelete': 'Reject and delete',
  'worldModel.draftReview.rejectAllTitle': ({ kind }) => `Reject all ${String(kind ?? '').toLowerCase()}?`,
  'worldModel.draftReview.rejectAllDescription': ({ count, kind }) => `This will delete ${String(count ?? 0)} draft ${String(kind ?? '').toLowerCase()}.\nThis cannot be undone.`,

  'worldModel.onboarding.title': 'Build the world model before you start writing',
  'worldModel.onboarding.description': 'You can generate drafts from setting text, or extract entities and relationships from uploaded chapters.',
  'worldModel.onboarding.generateTitle': 'Generate from setting text',
  'worldModel.onboarding.generateDescription': 'Paste world-setting text so AI can extract draft entities, relationships, and systems for you to confirm one by one.',
  'worldModel.onboarding.extractTitle': 'Extract from chapters',
  'worldModel.onboarding.extractDescription': 'Automatically extract draft entities and relationships from the chapters you already uploaded.',
  'worldModel.onboarding.extractUnavailable': 'Upload chapter content first so extraction can run.',
  'worldModel.onboarding.dismiss': 'Go to the world-model page and add it later →',
  'studio.preparation.title': 'Preparing this project',
  'studio.preparation.uploadDescription': 'NovWr is importing the chapters now. Once that finishes, it will extract entities and relationships automatically, so please wait a moment before doing anything else.',
  'studio.preparation.bootstrapDescription': 'The chapters are imported and NovWr is now extracting entities and relationships automatically.',
  'studio.preparation.failedTitle': 'Automatic extraction did not finish',
  'studio.preparation.failedDescription': 'The chapters were imported, but automatic entity and relationship extraction failed. You can retry now or come back to it later.',
  'studio.preparation.retry': 'Retry extraction',
  'studio.preparation.defer': 'Handle later',
  'studio.preparation.stage.accepted': 'Upload accepted and queued for import',
  'studio.preparation.stage.decoding': 'Reading the uploaded file',
  'studio.preparation.stage.parsing': 'Parsing the chapter structure',
  'studio.preparation.stage.planning': 'Planning the background work',
  'studio.preparation.stage.persisting': 'Writing chapter content',
  'studio.preparation.stage.completed': 'Import completed',
  'studio.preparation.stage.failed': 'Import failed',
  'studio.demoGuide.eyebrow': 'Demo-first onboarding',
  'studio.demoGuide.title': 'Walk the writing loop once before you import your own manuscript',
  'studio.demoGuide.description': 'This sample project is here to teach the NovWr workflow: inspect the world model first, return to Studio to find the continuation breakpoint, then use whole-book retrieval and Copilot for follow-up checks.',
  'studio.demoGuide.completedTitle': 'You have already walked the full sample workflow',
  'studio.demoGuide.completedDescription': 'The guide now stays tucked away, but you can reopen it anytime if you want to revisit each entry point.',
  'studio.demoGuide.skippedTitle': 'You hid this sample guide for now',
  'studio.demoGuide.skippedDescription': 'A lightweight reopen entry stays in the Studio rail, so you can expand the guide again whenever you want.',
  'studio.demoGuide.progress': ({ current, total }) => `${String(current ?? 0)}/${String(total ?? 4)} complete`,
  'studio.demoGuide.summaryChapters': ({ count }) => `${String(count ?? 0)} sample chapters`,
  'studio.demoGuide.summaryWorld': ({ entityCount, systemCount }) => `${String(entityCount ?? 0)} entities · ${String(systemCount ?? 0)} systems`,
  'studio.demoGuide.summaryLatest': ({ chapter }) => `Continuation breakpoint: ${String(chapter ?? '')}`,
  'studio.demoGuide.summaryLatestFallback': 'Continuation breakpoint coming later',
  'studio.demoGuide.chapterTitle': 'Read the sample inside Studio first',
  'studio.demoGuide.chapterDescription': 'Start with the chapter structure, current prose, and saved-chapter presentation before you decide to run the first continuation.',
  'studio.demoGuide.chapterAction': 'Open the sample chapter',
  'studio.demoGuide.worldModelTitle': 'Inspect the world model first',
  'studio.demoGuide.worldModelDescription': 'Use Atlas to review entities, relationships, and systems so you can see how this sample turns setting knowledge into something the app can retrieve.',
  'studio.demoGuide.worldModelAction': 'Open Atlas world model',
  'studio.demoGuide.breakpointTitle': 'Start the first continuation from one breakpoint',
  'studio.demoGuide.breakpointDescription': ({ chapter }) => `Use “${String(chapter ?? '')}” as the first continuation breakpoint and jump straight into the writing workspace.`,
  'studio.demoGuide.breakpointDescriptionFallback': 'The sample breakpoint is still blank, so start by reviewing the world model and chapter flow.',
  'studio.demoGuide.breakpointAction': 'Open the writing workspace',
  'studio.demoGuide.copilotTitle': 'Then use Novel Copilot for whole-book checks',
  'studio.demoGuide.copilotDescription': 'When you need to verify a character, rule, or clue across chapters, open Copilot and see how the sample relies on whole-book retrieval.',
  'studio.demoGuide.copilotAction': 'Open Novel Copilot',
  'studio.demoGuide.windowIndexLabel': 'Window Index:',
  'studio.demoGuide.complete': 'Complete',
  'studio.demoGuide.autoHideHint': 'Once all steps are complete, the guide will tuck itself away. You can also skip it now.',
  'studio.demoGuide.skip': 'Skip guide',
  'studio.demoGuide.reopen': 'Open demo guide',

  'worldModel.placeholder.key': 'Key',
  'worldModel.placeholder.value': 'Value',
  'worldModel.placeholder.name': 'Name',
  'worldModel.placeholder.description': 'Description',
  'worldModel.placeholder.nodeName': 'Node name',
  'worldModel.placeholder.eventName': 'Event name',
  'worldModel.placeholder.time': 'Time',
  'worldModel.placeholder.constraint': 'Constraint',
  'worldModel.placeholder.systemName': 'System name',

  'worldModel.error.deleteFailed': 'Delete failed. Please try again.',
  'worldModel.error.saveFailed': 'Save failed. Please try again.',
  'worldModel.error.confirmFailed': 'Confirm failed. Please try again.',
  'worldModel.error.rejectFailed': 'Reject failed. Please try again.',
  'worldModel.error.bootstrapTriggerFailed': 'Action failed. Please try again.',

  'chapter.loadingContent': 'Loading chapter content...',
  'chapter.emptySelectToRead': 'Select a chapter to start reading',

  'worldpack.import.warning.ambiguous_alias': ({ alias, entity_keys }) =>
    `Alias "${String(alias ?? '')}" points to multiple entities: ${String(entity_keys ?? '')}`,
  'worldpack.import.warning.entity_missing_name': ({ key }) =>
    `Entity "${String(key ?? '')}" is missing a name and was skipped`,
  'worldpack.import.warning.entity_missing_name_preserve_existing': ({ key }) =>
    `Entity "${String(key ?? '')}" is missing a name; the existing row was kept for relationship resolution`,
  'worldpack.import.warning.entity_name_conflict': ({ name }) =>
    `Entity name "${String(name ?? '')}" already exists and is bound to another worldpack identity, so it was skipped`,
  'worldpack.import.warning.entity_linked_by_name': ({ key, name }) =>
    `Entity "${String(key ?? '')}" was linked to an existing row by name "${String(name ?? '')}"`,
  'worldpack.import.warning.relationship_missing_label': 'A relationship was missing its label and was skipped',
  'worldpack.import.warning.relationship_missing_refs': ({ source_key, target_key }) =>
    `A relationship is missing references: source_key='${String(source_key ?? '')}', target_key='${String(target_key ?? '')}'`,
  'worldpack.import.warning.system_missing_name': 'A system was missing its name and was skipped',
  'worldpack.import.warning.system_name_conflict': ({ name }) =>
    `System name "${String(name ?? '')}" is already used by another pack, so it was skipped`,
  'worldpack.import.warning.skip_delete_promoted_entity': ({ key }) =>
    `Entity "${String(key ?? '')}" has non-worldpack dependencies and was preserved`,
  'worldpack.import.warning.preserved_entities_skipped': ({ count, sample }) =>
    `Skipped overwriting ${String(count ?? 0)} protected entities: ${String(sample ?? '')}`,
  'worldpack.import.warning.preserved_attributes_skipped': ({ count, sample, more_entities_count }) =>
    `Skipped overwriting ${String(count ?? 0)} protected attributes: ${String(sample ?? '')}${
      Number(more_entities_count ?? 0) > 0 ? ` (+${String(more_entities_count ?? 0)} more entities)` : ''
    }`,
  'worldpack.import.warning.preserved_relationships_skipped': ({ count, sample }) =>
    `Skipped overwriting ${String(count ?? 0)} protected relationships: ${String(sample ?? '')}`,
  'worldpack.import.warning.preserved_systems_skipped': ({ count, sample }) =>
    `Skipped overwriting ${String(count ?? 0)} protected systems: ${String(sample ?? '')}`,
  'worldpack.import.warning.duplicate_entity_key': ({ key }) =>
    `Duplicate entity key "${String(key ?? '')}" found in the payload and skipped`,

  'world.generate.warning.system_item_missing_time': 'A timeline item was missing its time and was skipped',
  'world.generate.warning.system_display_type_conflict': ({ name, downgraded_display_type }) =>
    `System "${String(name ?? '')}" had conflicting structure types across chunks, so it was downgraded to ${String(downgraded_display_type ?? '')}`,
  'world.generate.warning.entity_missing_name': 'An entity had an empty name and was skipped',
  'world.generate.warning.relationship_missing_fields': 'A relationship was missing source, target, or label and was skipped',
  'world.generate.warning.relationship_unknown_entity': ({ source, target }) =>
    `A relationship referenced an unknown entity and was discarded (${String(source ?? '')} -> ${String(target ?? '')})`,
  'world.generate.warning.relationship_self_reference': ({ entity }) =>
    `A relationship pointed back to the same entity and was skipped (${String(entity ?? '')})`,
  'world.generate.warning.relationship_duplicate': ({ label }) =>
    `A duplicate relationship was discarded (${String(label ?? '')})`,
  'world.generate.warning.system_missing_name': 'A system had an empty name and was skipped',
  'world.generate.warning.system_duplicate': ({ name }) =>
    `A duplicate system name was discarded (${String(name ?? '')})`,
  'world.generate.warning.system_name_conflict': ({ name }) =>
    `A system name already exists and was skipped (${String(name ?? '')})`,

  'continuation.prosecheck.warning.repeated_ngram': ({ phrase, count }) =>
    `Repeated phrase "${String(phrase ?? '')}" detected (${String(count ?? 0)} times)`,
  'continuation.prosecheck.warning.long_paragraph': ({ length, unit }) =>
    `Long paragraph detected (about ${String(length ?? 0)} ${String(unit ?? '')})`,
  'continuation.prosecheck.warning.abnormal_sentence_length': ({ length, unit }) =>
    `Long sentence detected (about ${String(length ?? 0)} ${String(unit ?? '')})`,
  'continuation.prosecheck.warning.summary_tone': ({ phrase }) =>
    `Summary/analysis-style wording "${String(phrase ?? '')}" detected and may not fit body prose`,
  // -- Continuation Setup --
  'continuation.setup.basedOn': ({ chapter }) => `Continue from ${String(chapter ?? '')}`,
  'continuation.setup.charCount': ({ count }) => `${String(count ?? 0)} chars`,
  'continuation.setup.loadingChapter': 'Loading chapter content...',
  'continuation.setup.emptyChapter': 'No chapter content yet',
  'continuation.setup.title': 'Continuation settings',
  'continuation.setup.instruction': 'Continuation instruction (optional)',
  'continuation.setup.instructionPlaceholder': 'Describe the plot direction you want, or leave blank for free continuation',
  'continuation.setup.length': 'Continuation length',
  'continuation.setup.advancedSettings': 'Advanced settings',
  'continuation.setup.contextChapters': 'Context chapters',
  'continuation.setup.numVersions': 'Versions to generate',
  'continuation.setup.temperature': 'Temperature',
  'continuation.setup.generate': 'Generate continuation',

  // -- Continuation Results --
  'continuation.results.loading': 'Loading continuation results...',
  'continuation.results.retry': 'Retry',
  'continuation.results.back': 'Back',
  'continuation.results.noResults': 'No continuation results found. Please regenerate from the workspace.',
  'continuation.results.returnToWorkspace': 'Return to workspace',
  'continuation.results.quotaExhausted': 'Generation quota exhausted',
  'continuation.results.serviceBusy': 'The service is busy right now. Please try again later.',
  'continuation.results.alreadyRunning': 'This continuation is already running. Please wait for the current result.',
  'continuation.results.requestFailed': ({ status }) => `Request failed (HTTP ${String(status ?? '')})`,
  'continuation.results.streamFallbackNotice': 'Live streaming was unstable on this network, so the app switched to a stable non-stream response automatically.',
  'continuation.results.quotaFeedback': 'Submit feedback to earn extra generation quota and keep writing.',
  'continuation.results.submitFeedbackUnlock': 'Submit feedback, unlock quota',
  'continuation.results.feedbackAlreadyClaimed': 'Feedback quota already claimed. You can configure your own API Key in Settings to continue.',
  'continuation.results.goToSettings': 'Go to Settings',
  'continuation.results.badge': 'Continuation results',
  'continuation.results.continuationOf': ({ chapter }) => `continuation of ${String(chapter ?? '')}`,
  'continuation.results.generating': 'Generating',
  'continuation.results.adopt': 'Adopt this version',
  'continuation.results.regenerate': 'Regenerate',
  'continuation.results.exportAll': 'Export all',
  'continuation.results.version': ({ n }) => `Version ${String(n ?? '')}`,
  'continuation.results.injectionSummary': ({ entities, relationships, systems }) =>
    `Injection summary (${String(entities ?? 0)} entities, ${String(relationships ?? 0)} relationships, ${String(systems ?? 0)} systems)`,
  'continuation.results.emptyContent': 'No content yet',
  'continuation.results.exportVersionHeader': ({ n }) => `========== Version ${String(n ?? '')} ==========`,

  // -- Chapter Editor --
  'editor.undo': 'Undo',
  'editor.redo': 'Redo',
  'editor.driftWarning': 'Drift warnings',
  'editor.charCount': ({ count }) => `${String(count ?? 0)} chars`,
  'editor.cursorPosition': ({ para, col }) => `Para ${String(para ?? 0)} · Col ${String(col ?? 0)}`,
  'editor.autoSaved': 'Auto-saved',
  'editor.unsaved': 'Unsaved changes',
  'editor.save': 'Save',

  // -- Drift Warning Popover --
  'drift.unknownTerm': 'Unknown term',
  'drift.unknownNaming': 'Unknown naming',
  'drift.unknownDefault': 'Unknown term',
  'drift.dismiss': 'Dismiss',

  // -- Prose Warnings Panel --
  'prose.repeatedNgram': 'Repeated phrase',
  'prose.longParagraph': 'Long paragraph',
  'prose.abnormalSentenceLength': 'Long sentence',
  'prose.summaryTone': 'Summary tone',
  'prose.checkTitle': ({ count }) => `Prose quality check (${String(count ?? 0)} ${Number(count) === 1 ? 'issue' : 'issues'})`,
  'prose.itemCount': ({ count }) => `${String(count ?? 0)} ${Number(count) === 1 ? 'item' : 'items'}`,
  'prose.candidate': ({ n }) => `Candidate ${String(n ?? '')}`,

  // -- Studio Page --
  'studio.chapter.deleteConfirm': ({ chapter }) => `Delete ${String(chapter ?? '')}? This cannot be undone.`,
  'studio.chapter.editing': 'Editing',
  'studio.chapter.reading': 'Reading',
  'studio.chapter.titlePlaceholder': 'Enter chapter title',
  'studio.chapter.titleEditHint': 'Double-click to edit title',
  'studio.chapter.titleAddHint': 'Double-click to add title',
  'studio.header.workspace': 'Chapter workspace',
  'studio.header.selectChapter': 'Select chapter',
  'studio.actions.moreActions': 'More actions',
  'studio.actions.exportAllChapters': 'Export all chapters',
  'studio.loading': 'Loading...',
  'studio.novelNotFound': 'Novel not found',
  'studio.chapter.charCount': ({ count }) => `${String(count ?? 0)} chars`,
  'studio.chapter.updated': ({ time }) => `updated ${String(time ?? '')}`,
  'studio.chapter.edit': 'Edit',
  'studio.chapter.delete': 'Delete chapter',
  'studio.rail.workspace': 'Workspace',
  'studio.rail.continuationTitle': 'Continuation settings',
  'studio.rail.continuationDescription': ({ chapter }) => `Set up the next continuation from ${String(chapter ?? '')}`,
  'studio.rail.atlasTitle': 'Atlas world model',
  'studio.rail.atlasDescription': 'Open the relationship graph, review queue, and deep-governance tools',
  'studio.rail.searchChapters': 'Search chapters...',
  'studio.rail.searchResults': ({ count }) => `Search results: ${String(count ?? 0)} ${Number(count) === 1 ? 'item' : 'items'}`,
  'studio.rail.chapters': 'Chapters',
  'studio.rail.createChapter': 'Create chapter',
  'studio.rail.noChapters': 'No chapters yet',
  'studio.rail.chapterCount': ({ count }) => `${String(count ?? 0)} ${Number(count) === 1 ? 'chapter' : 'chapters'}`,
  'studio.stage.returnToResults': 'Back to results',
  'studio.stage.openInAtlas': 'Open in Atlas',
  'studio.stage.entity.title': 'Entity check',
  'studio.stage.entity.description': 'Review and lightly edit entities tied to the current context. Deeper structural governance still belongs in Atlas.',
  'studio.stage.entity.openCopilot': 'Entity copilot',
  'studio.stage.relationship.title': 'Relationship check',
  'studio.stage.relationship.currentEntity': 'the current entity',
  'studio.stage.relationship.description': ({ subject }) => `Review relationship descriptions, consistency, and draft confirmation around ${String(subject ?? '')} in a lightweight way; graph and topology changes still belong in Atlas.`,
  'studio.stage.relationship.openCopilot': 'Relationship copilot',
  'studio.stage.relationship.noContext': 'No entity context is available to review.',
  'studio.stage.relationship.entityWithId': ({ id }) => `Entity ${String(id ?? '')}`,
  'studio.stage.relationship.forEntity': ({ subject }) => `${String(subject ?? '')} relationships`,
  'studio.stage.relationship.count': ({ count }) => `${String(count ?? 0)} ${Number(count) === 1 ? 'relationship' : 'relationships'}`,
  'studio.stage.relationship.empty': 'No relationships yet',
  'studio.stage.relationship.unnamed': 'Unnamed relationship',
  'studio.stage.draftReview.title': 'Draft review',
  'studio.stage.draftReview.description': 'Handle individual drafts quickly in the writing context. Batch governance and denser work stay in Atlas.',
  'studio.stage.system.title': 'System check',
  'studio.stage.system.description': 'Review system descriptions and visibility in the writing context. Structural editing, constraint maintenance, and deeper governance still belong in Atlas.',
  'studio.stage.system.sidebarTitle': 'World systems',
  'studio.stage.system.count': ({ count }) => `${String(count ?? 0)} ${Number(count) === 1 ? 'system' : 'systems'}`,
  'studio.stage.system.empty': 'No systems yet',
  'studio.stage.system.unnamed': 'Unnamed system',
  'studio.stage.system.selectPrompt': 'Select a system to start reviewing.',
  'studio.stage.system.confirm': 'Confirm system',
  'studio.stage.system.help': 'Studio only handles lightweight system review and metadata edits. Move to Atlas for constraints, hierarchy/timeline/list structures, and deeper editing.',
  'studio.stage.system.descriptionSection': 'Description',
  'studio.stage.system.summary.legacyGraph': 'Legacy graph type. Full read-only inspection is available only in Atlas.',
  'studio.stage.system.summary.hierarchy': ({ count }) => `${String(count ?? 0)} hierarchy ${Number(count) === 1 ? 'node' : 'nodes'}`,
  'studio.stage.system.summary.timeline': ({ count }) => `${String(count ?? 0)} timeline ${Number(count) === 1 ? 'event' : 'events'}`,
  'studio.stage.system.summary.list': ({ count }) => `${String(count ?? 0)} ${Number(count) === 1 ? 'list rule' : 'list rules'}`,
  'studio.assistant.toggleSidebar': 'Toggle AI sidebar',
  'studio.research.eyebrow': 'Research entry',
  'studio.research.title': 'Research first, then decide what should enter governance',
  'studio.research.description': 'Open Novel Copilot whole-book research here when you need cross-chapter checks on characters, lore gaps, or recurring clues.',
  'studio.research.openWholeBook': 'Open whole-book research',
  'studio.research.openWholeBookHint': 'Search recurring clues, world-model gaps, and the anchors most worth investigating next.',
  'studio.research.contextualEyebrow': 'Current context',
  'studio.worldEntry.eyebrow': 'World entry',
  'studio.worldEntry.title': 'Send world-building work into Atlas',
  'studio.worldEntry.reviewHint': 'Generation and extraction only create intake work. Formal review and governance still happen in Atlas.',
  'studio.worldEntry.summary': ({ entityCount, systemCount }) => `Current world: ${String(entityCount ?? 0)} ${Number(entityCount) === 1 ? 'entity' : 'entities'} · ${String(systemCount ?? 0)} ${Number(systemCount) === 1 ? 'system' : 'systems'}`,
  'studio.worldEntry.summaryEmpty': 'No entities or systems exist yet',
  'studio.worldEntry.attention.eyebrow': 'Atlas handoff',
  'studio.worldEntry.attention.runningTitle': 'World sync is still running',
  'studio.worldEntry.attention.runningDescription': 'Check the world-entry status below first, then decide whether Atlas needs your attention.',
  'studio.worldEntry.attention.failedTitle': 'This world sync was interrupted',
  'studio.worldEntry.attention.failedDescription': 'Continue from the world-entry section below or retry extraction before leaving Studio.',
  'studio.worldEntry.attention.reviewTitle': 'Atlas already has new drafts waiting for review',
  'studio.worldEntry.attention.reviewDescription': 'These world drafts are ready now, so review is the higher-priority next step.',
  'studio.worldEntry.attention.showPanel': 'Show entry',
  'studio.worldEntry.handoff.reviewReadyTitle': 'Drafts have been sent into Atlas — review comes next',
  'studio.worldEntry.handoff.reviewReadyDescription': 'Studio only launches the intake. Formal review and governance still happen in Atlas.',
  'studio.worldEntry.handoff.syncCompleteTitle': 'Sync complete',
  'studio.worldEntry.handoff.syncCompleteDescription': 'There was no forced route takeover. Keep writing now, or open Atlas later when you are ready.',
  'studio.worldEntry.handoff.extractRunningTitle': 'Chapter extraction is still syncing world drafts',
  'studio.worldEntry.handoff.extractRunningDescription': 'You can stay in Studio while it runs, then open Atlas review when the sync finishes.',
  'studio.worldEntry.handoff.extractFailedTitle': 'Chapter extraction did not finish',
  'studio.worldEntry.handoff.extractFailedDescription': 'Retry extraction first. If you only need to inspect the current world state, you can still open Atlas.',
  'studio.worldEntry.handoff.openReview': 'Open draft review',
  'studio.worldEntry.handoff.openAtlas': 'Open Atlas',
  'studio.worldEntry.handoff.runningState': 'Running',
  'studio.worldEntry.handoff.failedState': 'Failed',
  'studio.worldEntry.handoff.reviewState': 'Needs review',
  'studio.worldEntry.handoff.successState': 'Synced',
  'studio.contextualCopilot.entity.title': 'Entity enrichment',
  'studio.contextualCopilot.entity.description': ({ subject }) => `Keep enriching “${String(subject ?? '')}” with setting details, supporting evidence, and attributes.`,
  'studio.contextualCopilot.entity.descriptionFallback': 'Keep enriching the current entity with setting details and attributes.',
  'studio.contextualCopilot.relationship.title': 'Relationship enrichment',
  'studio.contextualCopilot.relationship.description': ({ subject }) => `Keep reviewing and enriching the relationship network around “${String(subject ?? '')}”.`,
  'studio.contextualCopilot.relationship.descriptionFallback': 'Keep reviewing relationship clues connected to the current entity.',
  'studio.injectionSummary.title': ({ count }) => `Injection summary · ${String(count ?? 0)} ${Number(count) === 1 ? 'item' : 'items'}`,
  'studio.injectionSummary.empty': 'No injected content',
  'studio.injectionSummary.openInAtlas': 'View everything in Atlas',
} as const satisfies Record<keyof typeof novelZhMessages, UiMessageValue>

export const novelUiMessages = {
  zh: novelZhMessages,
  en: novelEnMessages,
} as const

registerUiMessages(novelUiMessages)
