"""Compatibility facade for state-proto callers.

New internal imports should target ``state_proto_model``, ``state_proto_runtime``,
or ``state_proto_executor`` directly so the facade remains a stable boundary for
tests and older callers instead of becoming the package's main dependency path.
"""

from .state_proto_executor import execute_state_proto_build
from .state_proto_model import (
    CUE_ASSERTED,
    CUE_HISTORICAL,
    CUE_HYPOTHETICAL,
    CUE_NEGATED,
    DEFAULT_CJK_OPEN_CHARS,
    DEFAULT_CJK_PREVIEW_CHARS,
    DEFAULT_NON_CJK_OPEN_CHARS,
    DEFAULT_NON_CJK_PREVIEW_CHARS,
    ClaimAtom,
    ClaimKey,
    CandidateStatePack,
    CoverageRepresentative,
    PackProvenance,
    Regime,
    SCRIPT_MODE_CJK_HEAVY,
    SCRIPT_MODE_SPACE_DELIMITED,
    SLOT_ARTIFACT_CURRENT_OWNER,
    SLOT_ENTITY_CURRENT_AFFILIATION,
    SLOT_ENTITY_CURRENT_LOCATION,
    SLOT_ENTITY_CURRENT_ROLE,
    SLOT_ENTITY_LIFE_STATE,
    SUPPORTED_CLAIM_SLOTS,
    STATE_PROTO_EXECUTOR_BACKEND_NONE,
    STATE_PROTO_EXECUTOR_BACKEND_RUST,
    Segment,
    SourceOpenPayload,
    StateProtoArtifacts,
    StateProtoBuildOutput,
    StateProtoChapterShard,
    SlotTracePack,
    TARGET_KIND_ARTIFACT,
    TARGET_KIND_ENTITY,
    TargetSpec,
    UNCERTAINTY_AMBIGUOUS_CUE,
    UNCERTAINTY_FRESH_CONFLICT,
    UNCERTAINTY_LOW_MARGIN,
    UNCERTAINTY_SPARSE_TAIL,
    compute_state_proto_chapter_signature,
)
from .state_proto_runtime import StateProtoIndex, _detect_script_mode

__all__ = [
    "CUE_ASSERTED",
    "CUE_HISTORICAL",
    "CUE_HYPOTHETICAL",
    "CUE_NEGATED",
    "DEFAULT_CJK_OPEN_CHARS",
    "DEFAULT_CJK_PREVIEW_CHARS",
    "DEFAULT_NON_CJK_OPEN_CHARS",
    "DEFAULT_NON_CJK_PREVIEW_CHARS",
    "CandidateStatePack",
    "ClaimAtom",
    "ClaimKey",
    "CoverageRepresentative",
    "PackProvenance",
    "Regime",
    "SCRIPT_MODE_CJK_HEAVY",
    "SCRIPT_MODE_SPACE_DELIMITED",
    "SLOT_ARTIFACT_CURRENT_OWNER",
    "SLOT_ENTITY_CURRENT_AFFILIATION",
    "SLOT_ENTITY_CURRENT_LOCATION",
    "SLOT_ENTITY_CURRENT_ROLE",
    "SLOT_ENTITY_LIFE_STATE",
    "SUPPORTED_CLAIM_SLOTS",
    "STATE_PROTO_EXECUTOR_BACKEND_NONE",
    "STATE_PROTO_EXECUTOR_BACKEND_RUST",
    "Segment",
    "SourceOpenPayload",
    "StateProtoArtifacts",
    "StateProtoBuildOutput",
    "StateProtoChapterShard",
    "StateProtoIndex",
    "SlotTracePack",
    "TARGET_KIND_ARTIFACT",
    "TARGET_KIND_ENTITY",
    "TargetSpec",
    "UNCERTAINTY_AMBIGUOUS_CUE",
    "UNCERTAINTY_FRESH_CONFLICT",
    "UNCERTAINTY_LOW_MARGIN",
    "UNCERTAINTY_SPARSE_TAIL",
    "_detect_script_mode",
    "compute_state_proto_chapter_signature",
    "execute_state_proto_build",
]
